import { TelecomStepData, TelecomTechnology } from './types';

export const TELECOM_STEPS: TelecomStepData[] = [
  {
    id: '01',
    number: '01',
    stageName: 'Call Connection',
    shortTitle: 'Inbound Call',
    actor: 'Farmer → Exotel',
    summary:
      "The farmer dials the VidhAI access number from any feature phone or smartphone without needing an internet connection. Exotel instantly accepts the call and initiates a bidirectional WebSocket audio stream with VidhAI's backend.",
    details: [
      'Farmer places a voice call to the designated VidhAI telephony number.',
      "Exotel connects the call to the backend infrastructure with zero application install required by the farmer.",
      "Streams incoming caller PCM audio directly through an ultra-low-latency bidirectional WebSocket connection.",
    ],
    providers: [
      { name: 'Exotel', role: 'Telephony Gateway & Inbound Bridge', isPrimary: true },
      { name: 'Node.js', role: 'Bidirectional WebSocket Server', isPrimary: true },
    ],
    category: 'telephony',
    technicalBadge: 'Bidirectional WebSocket',
    relatedTechIds: ['exotel', 'nodejs', 'render'],
  },
  {
    id: '02',
    number: '02',
    stageName: 'Caller Identification',
    shortTitle: 'Caller ID & Onboarding',
    actor: 'VidhAI Identity Gateway',
    summary:
      'VidhAI extracts the caller’s telephone number to look up existing agrarian profiles. Returning farmers have their farm context loaded immediately, while first-time callers are seamlessly guided into voice onboarding.',
    details: [
      'Extracts incoming caller CLI (phone number) from the telephony metadata packet.',
      'Queries Firebase Firestore for matching registered farmer profiles, active land parcels, and preferred dialect.',
      'Enables rapid voice onboarding for new callers to collect language preference, name, village location, and landholding details.',
    ],
    branching: [
      {
        label: 'Existing Caller',
        action: 'Loads saved profile, localized language preference, crop records, and prior conversation memory.',
      },
      {
        label: 'New Caller',
        action: 'Starts conversational voice onboarding to collect dialect, name, district location, and farm details.',
      },
    ],
    providers: [
      { name: 'Firebase Firestore', role: 'Caller Registry & Farm Graph', isPrimary: true },
      { name: 'Express', role: 'Identity Session Controller', isPrimary: false },
    ],
    category: 'telephony',
    technicalBadge: 'Profile Ingestion & Onboarding',
    relatedTechIds: ['firebase-firestore', 'express'],
  },
  {
    id: '03',
    number: '03',
    stageName: 'Audio Processing',
    shortTitle: 'Audio Pipeline',
    actor: 'Telephony Signal Pipeline',
    summary:
      'Incoming 8kHz/16kHz telephone audio undergoes real-time signal enhancement. The backend detects vocal presence, separates silence pauses, buffers complete utterances, and normalizes gain for transcription.',
    details: [
      'Executes real-time Voice Activity Detection (VAD) to identify speech onset, conversational interjections, and natural pauses.',
      'Buffers incoming raw audio packets into coherent utterance frames while stripping telephony background noise.',
      'Applies dynamic gain control and sample rate normalization to prepare optimized audio buffers for speech-to-text models.',
    ],
    providers: [
      { name: 'Node.js', role: 'Real-Time Audio Frame Pipeline', isPrimary: true },
      { name: 'TypeScript', role: 'Type-Safe Audio Buffer Protocol', isPrimary: false },
    ],
    category: 'telephony',
    technicalBadge: 'VAD & Utterance Buffering',
    relatedTechIds: ['nodejs', 'typescript'],
  },
  {
    id: '04',
    number: '04',
    stageName: 'Speech-to-Text',
    shortTitle: 'Speech Recognition',
    actor: 'Language-Aware STT Router',
    summary:
      'A dynamic speech recognition router selects the best multilingual model based on the caller’s dialect. Dedicated regional models decode Tamil and mixed vernacular speech with high phonetic accuracy, supported by resilient recovery paths.',
    details: [
      'Sarvam AI (Saaras v4): Specialized high-accuracy transcription for Tamil and mixed Tamil-English rural conversational speech.',
      'Groq (Whisper Large V3 / Turbo): Sub-second transcription for English and other Indian languages with automatic language detection and error recovery.',
      'NVIDIA (Parakeet): Language-aware acoustic model optimized for Hindi and North Indian agricultural vocabulary.',
      'Configured recovery path: If audio is ambiguous or noisy, triggers adaptive thresholding and secondary transcription fallbacks.',
    ],
    providers: [
      { name: 'Sarvam AI — Saaras v4', role: 'Tamil & Tamil-English Speech Recognition', isPrimary: true },
      { name: 'Groq — Whisper Large V3 / Turbo', role: 'English, Multilingual & Recovery Routing', isPrimary: true },
      { name: 'NVIDIA — Parakeet', role: 'Hindi & Multilingual STT Model', isPrimary: false },
    ],
    category: 'stt',
    technicalBadge: 'Language-Aware STT Routing',
    relatedTechIds: ['sarvam-stt', 'groq-whisper', 'nvidia-parakeet'],
  },
  {
    id: '05',
    number: '05',
    stageName: 'AI Understanding',
    shortTitle: 'AI Reasoning & Tools',
    actor: 'Groq openai/gpt-oss-20b',
    summary:
      'The central conversation layer synthesizes the transcript, caller context, historical dialog turns, and farm records. Groq’s openai/gpt-oss-20b performs conversational reasoning, orchestrates tool calling, and decides service routing.',
    details: [
      'Receives verified transcript, caller’s selected language, prior conversation turns, and verified farm context.',
      'Groq openai/gpt-oss-20b maintains dialog state, analyzes agronomic intent, and formulates precise conversational responses.',
      'Employs structured action handlers and tool calling to dispatch data queries to weather, mandi, and profile services.',
    ],
    providers: [
      { name: 'Groq — openai/gpt-oss-20b', role: 'Conversational LLM & Tool Orchestrator', isPrimary: true },
      { name: 'TypeScript', role: 'Structured Tool Handlers & Schema Contracts', isPrimary: false },
    ],
    category: 'reasoning',
    technicalBadge: 'Contextual LLM & Tool Calls',
    relatedTechIds: ['groq-llm', 'typescript', 'express'],
  },
  {
    id: '06',
    number: '06',
    stageName: 'Information Retrieval / Action',
    shortTitle: 'Connected Services',
    actor: 'Service Hub & Integrations',
    summary:
      'Action handlers execute live queries against authoritative external agricultural services. Weather telemetry, localized commodity rates, and farmer memory are fetched concurrently to ground the response in verified reality.',
    details: [
      'Weather Telemetry: Open-Meteo provides hyperlocal rainfall probabilities, temperatures, and wind advisories.',
      'Mandi Market Prices: Tamil Nadu Agrimark / Agmarknet v2 yields normalized ₹/kg commodity prices, with legacy data.gov.in as a reliable fallback.',
      'Farmer Information: Firebase Firestore delivers farmer profiles, farm parcels, conversation history, memory records, and pending calendar reminders.',
      'Application microservices execute state updates for profile adjustments, task creation, and scheduled voice reminders.',
    ],
    providers: [
      { name: 'Open-Meteo', role: 'Hyperlocal Weather & Rain Telemetry', isPrimary: true },
      { name: 'Tamil Nadu Agrimark / Agmarknet v2', role: 'Normalized Mandi Price Telemetry', isPrimary: true },
      { name: 'Firebase Firestore', role: 'Farmer Profiles, Memory & Reminders', isPrimary: true },
    ],
    category: 'services',
    technicalBadge: 'Agronomic Telemetry & Data Hub',
    relatedTechIds: ['open-meteo', 'agmarknet', 'firebase-firestore'],
  },
  {
    id: '07',
    number: '07',
    stageName: 'Response Generation',
    shortTitle: 'Voice Generation',
    actor: 'Safety Filter & Voice Router',
    summary:
      'VidhAI condenses the agronomic finding into a concise, friendly spoken answer. Agricultural safety checks are applied before the text is dispatched to specialized voice synthesis engines with full regional fallback.',
    details: [
      'Prepares a succinct, conversational answer tailored for auditory comprehension over telephone speakers.',
      'Applies rigorous agricultural safety heuristics to verify pesticide guidelines, dosage recommendations, and weather-critical spraying advice.',
      'ElevenLabs (eleven_flash_v2_5): Preferred ultra-low-latency general voice synthesizer delivering natural pacing.',
      'Sarvam AI (Bulbul v3): Native Tamil voice synthesis tuned for regional cadence, serving as primary Tamil and configured voice fallback.',
      'Shunya Labs: Secondary text-to-speech fallback ensuring 100% voice continuity during peak network load.',
    ],
    providers: [
      { name: 'ElevenLabs — eleven_flash_v2_5', role: 'Preferred Low-Latency Voice Provider', isPrimary: true },
      { name: 'Sarvam AI — Bulbul v3', role: 'Tamil Voice Generation & Regional Fallback', isPrimary: true },
      { name: 'Shunya Labs', role: 'Secondary Text-to-Speech Fallback Engine', isPrimary: false },
    ],
    category: 'tts',
    technicalBadge: 'Safety Guardrails & Voice Synthesis',
    relatedTechIds: ['elevenlabs', 'sarvam-tts', 'shunya-labs'],
  },
  {
    id: '08',
    number: '08',
    stageName: 'Voice Response + Continuous Conversation',
    shortTitle: 'Telephone Playback',
    actor: 'Exotel + Bidirectional Audio Loop',
    summary:
      'Generated synthesized audio is chunked into telephone-compatible codecs and streamed through the WebSocket back to Exotel. The farmer hears the spoken response, and the loop stays active for follow-up questions until completion.',
    details: [
      'Synthesized audio buffers are re-encoded into telephone-compatible audio chunks (8kHz/16kHz u-law/PCM).',
      'The backend streams chunks over the WebSocket back into Exotel’s active call bridge with minimal latency.',
      'Exotel plays the audio to the farmer in real-time over the cellular network.',
      'Continuous Conversation Loop: The channel remains open so the farmer can speak again, ask follow-up questions, or conclude the call.',
      'All user inputs, model responses, and tool telemetry are logged in Firestore call history for continuity in future sessions.',
    ],
    providers: [
      { name: 'Exotel', role: 'Cellular Audio Playback & Call Bridge', isPrimary: true },
      { name: 'Node.js', role: 'WebSocket Stream Chunking & Queueing', isPrimary: true },
      { name: 'Firebase Firestore', role: 'Call History & Transcript Persistence', isPrimary: false },
    ],
    category: 'telephony',
    technicalBadge: 'Continuous Multi-Turn Audio Loop',
    relatedTechIds: ['exotel', 'nodejs', 'firebase-firestore', 'render'],
  },
];

export const TELECOM_TECHNOLOGIES: TelecomTechnology[] = [
  {
    id: 'exotel',
    name: 'Exotel',
    category: 'Telephony & Streaming',
    purpose: 'Powers telecom connectivity by receiving incoming phone calls and providing bidirectional WebSocket audio streaming.',
    badge: 'Telephony Gateway',
  },
  {
    id: 'sarvam-stt',
    name: 'Sarvam AI — Saaras v4',
    category: 'Speech-to-Text',
    purpose: 'Provides high-accuracy speech recognition specifically engineered for Tamil and mixed Tamil-English dialects.',
    badge: 'Tamil STT Model',
  },
  {
    id: 'groq-whisper',
    name: 'Groq — Whisper Large V3 / Turbo',
    category: 'Speech-to-Text',
    purpose: 'Delivers ultra-fast speech-to-text for English and multilingual audio alongside automated language detection and recovery.',
    badge: 'Fast Whisper STT',
  },
  {
    id: 'nvidia-parakeet',
    name: 'NVIDIA — Parakeet',
    category: 'Speech-to-Text',
    purpose: 'Supplies language-aware speech recognition with robust acoustic modeling particularly optimized for Hindi spoken queries.',
    badge: 'Acoustic Model',
  },
  {
    id: 'groq-llm',
    name: 'Groq — openai/gpt-oss-20b',
    category: 'Conversational AI',
    purpose: 'Maintains conversational dialog context, determines agricultural intent, and executes tool routing for appropriate actions.',
    badge: 'Central LLM Core',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs — eleven_flash_v2_5',
    category: 'Voice Synthesis',
    purpose: 'Serves as the preferred general voice provider generating ultra-low-latency, expressive speech for caller responses.',
    badge: 'Primary TTS Engine',
  },
  {
    id: 'sarvam-tts',
    name: 'Sarvam AI — Bulbul v3',
    category: 'Voice Synthesis',
    purpose: 'Generates natural Tamil spoken responses and provides a configured voice fallback for regional dialect accuracy.',
    badge: 'Tamil Voice Engine',
  },
  {
    id: 'shunya-labs',
    name: 'Shunya Labs',
    category: 'Voice Synthesis',
    purpose: 'Acts as an additional text-to-speech fallback provider ensuring uninterrupted voice response delivery under high traffic.',
    badge: 'Fallback TTS Engine',
  },
  {
    id: 'open-meteo',
    name: 'Open-Meteo',
    category: 'Connected Services',
    purpose: 'Delivers live hyperlocal weather forecasts, rainfall probabilities, and temperature telemetry for farm-level guidance.',
    badge: 'Weather API',
  },
  {
    id: 'agmarknet',
    name: 'Tamil Nadu Agrimark / Agmarknet v2',
    category: 'Connected Services',
    purpose: 'Supplies real-time agricultural market commodity pricing with standardized rates in ₹/kg and data.gov.in fallback.',
    badge: 'Mandi Telemetry',
  },
  {
    id: 'firebase-firestore',
    name: 'Firebase Firestore',
    category: 'Connected Services',
    purpose: 'Persists farmer profiles, landholding parcels, conversation history, memory states, and scheduled farm reminders.',
    badge: 'Real-Time Database',
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'Core Runtime & Cloud',
    purpose: 'Executes the event-driven server runtime managing concurrent telephone WebSockets and real-time audio chunk pipelines.',
    badge: 'Server Runtime',
  },
  {
    id: 'express',
    name: 'Express',
    category: 'Core Runtime & Cloud',
    purpose: 'Routes telephony webhooks, handles API authentication, and coordinates internal microservice dispatches.',
    badge: 'HTTP / API Gateway',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'Core Runtime & Cloud',
    purpose: 'Enforces end-to-end type safety across telephony events, tool call schemas, and connected service integration payloads.',
    badge: 'Type-Safe Contracts',
  },
  {
    id: 'render',
    name: 'Render',
    category: 'Core Runtime & Cloud',
    purpose: 'Hosts the cloud telephony backend with reliable uptime, automated deployments, and scalable network capacity.',
    badge: 'Cloud Hosting',
  },
];
