class CropKnowledgeEntry {
  final String id;
  final String name;
  final String variety;
  final String category;
  final String durationDays;
  final String durationCategory; // short, medium, long
  final List<String> suitableSoils;
  final String waterRequirement;
  final String suitableTemperature;
  final List<String> suitableStates;
  final List<String> suitableDistricts;
  final String agroClimaticZones;
  final String season; // kharif, rabi, zaid, all
  final String expectedYieldPerAcre;
  final String investmentPerAcre;
  final String revenuePerAcre;
  final String profitPerAcre;
  final String marketDemand;
  final String riskLevel;
  final String bestPlantingMonth;
  final String harvestMonth;
  final String description;

  const CropKnowledgeEntry({
    required this.id,
    required this.name,
    required this.variety,
    required this.category,
    required this.durationDays,
    required this.durationCategory,
    required this.suitableSoils,
    required this.waterRequirement,
    required this.suitableTemperature,
    required this.suitableStates,
    required this.suitableDistricts,
    required this.agroClimaticZones,
    required this.season,
    required this.expectedYieldPerAcre,
    required this.investmentPerAcre,
    required this.revenuePerAcre,
    required this.profitPerAcre,
    required this.marketDemand,
    required this.riskLevel,
    required this.bestPlantingMonth,
    required this.harvestMonth,
    required this.description,
  });
}

class CropKnowledgeBase {
  static final CropKnowledgeBase _instance = CropKnowledgeBase._();
  factory CropKnowledgeBase() => _instance;
  CropKnowledgeBase._();

  final List<CropKnowledgeEntry> _crops = _allCrops;
  List<CropKnowledgeEntry> get allCrops => List.unmodifiable(_crops);

  List<CropKnowledgeEntry> filter({
    String? state,
    String? district,
    String? soilType,
    String? waterAvailability,
    String? season,
    String? durationCategory,
    String? category,
  }) {
    return _crops.where((crop) {
      if (state != null && state.isNotEmpty) {
        final states = crop.suitableStates.map((s) => s.toLowerCase()).toList();
        if (!states.contains(state.toLowerCase()) &&
            !states.contains('all india')) {
          return false;
        }
      }
      if (district != null && district.isNotEmpty) {
        final districts =
            crop.suitableDistricts.map((d) => d.toLowerCase()).toList();
        if (!districts.contains(district.toLowerCase()) &&
            !districts.contains('all')) {
          return false;
        }
      }
      if (soilType != null && soilType.isNotEmpty) {
        final soils = crop.suitableSoils.map((s) => s.toLowerCase()).toList();
        if (!soils.contains(soilType.toLowerCase()) && !soils.contains('all')) {
          return false;
        }
      }
      if (waterAvailability != null && waterAvailability.isNotEmpty) {
        final wa = waterAvailability.toLowerCase();
        final req = crop.waterRequirement.toLowerCase();
        if (wa == 'no water' && req != 'low') return false;
        if (wa == 'very low' && (req == 'high' || req == 'very high')) {
          return false;
        }
        if (wa == 'low' && req == 'very high') return false;
      }
      if (season != null && season.isNotEmpty) {
        if (crop.season.toLowerCase() != 'all' &&
            crop.season.toLowerCase() != season.toLowerCase()) {
          return false;
        }
      }
      if (durationCategory != null && durationCategory.isNotEmpty) {
        if (crop.durationCategory != durationCategory) return false;
      }
      if (category != null && category.isNotEmpty) {
        if (crop.category.toLowerCase() != category.toLowerCase()) return false;
      }
      return true;
    }).toList();
  }
}

final List<CropKnowledgeEntry> _allCrops = [
  // CEREALS - PADDY
  const CropKnowledgeEntry(
      id: 'CR001',
      name: 'Paddy',
      variety: 'IR-64',
      category: 'Cereals',
      durationDays: '120-130',
      durationCategory: 'long',
      suitableSoils: ['Clay', 'Loamy', 'All'],
      waterRequirement: 'High',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Tamil Nadu',
        'Andhra Pradesh',
        'Telangana',
        'Punjab',
        'Haryana',
        'West Bengal',
        'Bihar',
        'Uttar Pradesh',
        'Kerala',
        'Karnataka',
        'Odisha',
        'Assam',
        'Chhattisgarh',
        'Madhya Pradesh',
        'Maharashtra',
        'Jharkhand',
        'All India'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '15-20 quintals',
      investmentPerAcre: '₹15,000-20,000',
      revenuePerAcre: '₹30,000-40,000',
      profitPerAcre: '₹10,000-20,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'October-November',
      description: 'Staple cereal grain, major food crop in India'),
  const CropKnowledgeEntry(
      id: 'CR002',
      name: 'Paddy',
      variety: 'Samba Mahsuri',
      category: 'Cereals',
      durationDays: '115-125',
      durationCategory: 'long',
      suitableSoils: ['Clay', 'Loamy', 'All'],
      waterRequirement: 'High',
      suitableTemperature: '20-35°C',
      suitableStates: ['Tamil Nadu', 'Andhra Pradesh', 'Karnataka'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '18-22 quintals',
      investmentPerAcre: '₹16,000-22,000',
      revenuePerAcre: '₹36,000-44,000',
      profitPerAcre: '₹15,000-22,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'October-November',
      description: 'Premium fine grain variety, popular in South India'),
  const CropKnowledgeEntry(
      id: 'CR003',
      name: 'Paddy',
      variety: 'Basmati 370',
      category: 'Cereals',
      durationDays: '130-150',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Sandy', 'All'],
      waterRequirement: 'High',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Punjab',
        'Haryana',
        'Uttar Pradesh',
        'Jammu and Kashmir'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '12-16 quintals',
      investmentPerAcre: '₹18,000-25,000',
      revenuePerAcre: '₹40,000-60,000',
      profitPerAcre: '₹18,000-35,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'November-December',
      description: 'Premium aromatic long grain rice, high export value'),

  // CEREALS - WHEAT
  const CropKnowledgeEntry(
      id: 'CR004',
      name: 'Wheat',
      variety: 'HD-3226',
      category: 'Cereals',
      durationDays: '115-130',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '10-25°C',
      suitableStates: [
        'Punjab',
        'Haryana',
        'Uttar Pradesh',
        'Madhya Pradesh',
        'Rajasthan',
        'Gujarat',
        'Bihar',
        'Maharashtra'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Rabi',
      expectedYieldPerAcre: '18-22 quintals',
      investmentPerAcre: '₹10,000-15,000',
      revenuePerAcre: '₹27,000-33,000',
      profitPerAcre: '₹12,000-18,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'October-November',
      harvestMonth: 'March-April',
      description: 'Major rabi cereal crop'),
  const CropKnowledgeEntry(
      id: 'CR005',
      name: 'Wheat',
      variety: 'PBW-725',
      category: 'Cereals',
      durationDays: '120-135',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay'],
      waterRequirement: 'Medium',
      suitableTemperature: '10-25°C',
      suitableStates: ['Punjab', 'Haryana', 'Rajasthan'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Rabi',
      expectedYieldPerAcre: '20-25 quintals',
      investmentPerAcre: '₹11,000-16,000',
      revenuePerAcre: '₹30,000-37,500',
      profitPerAcre: '₹15,000-21,500',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'November',
      harvestMonth: 'April',
      description: 'High yielding dwarf variety'),

  // MILLETS
  const CropKnowledgeEntry(
      id: 'CR006',
      name: 'Ragi (Finger Millet)',
      variety: 'KMR-204',
      category: 'Cereals',
      durationDays: '90-120',
      durationCategory: 'medium',
      suitableSoils: ['Sandy', 'Loamy', 'Clay', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Karnataka',
        'Tamil Nadu',
        'Andhra Pradesh',
        'Maharashtra',
        'Uttar Pradesh',
        'Rajasthan',
        'Odisha',
        'Madhya Pradesh'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '8-12 quintals',
      investmentPerAcre: '₹5,000-8,000',
      revenuePerAcre: '₹16,000-24,000',
      profitPerAcre: '₹8,000-16,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'September-October',
      description: 'Drought tolerant millet, rich in calcium'),
  const CropKnowledgeEntry(
      id: 'CR007',
      name: 'Pearl Millet (Bajra)',
      variety: 'HHB-67',
      category: 'Cereals',
      durationDays: '75-90',
      durationCategory: 'short',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '25-40°C',
      suitableStates: [
        'Rajasthan',
        'Gujarat',
        'Maharashtra',
        'Haryana',
        'Uttar Pradesh',
        'Madhya Pradesh',
        'Tamil Nadu',
        'Karnataka'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '10-15 quintals',
      investmentPerAcre: '₹4,000-6,000',
      revenuePerAcre: '₹12,000-18,000',
      profitPerAcre: '₹6,000-12,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'September-October',
      description: 'Heat and drought tolerant coarse cereal'),
  const CropKnowledgeEntry(
      id: 'CR008',
      name: 'Jowar (Sorghum)',
      variety: 'CSH-14',
      category: 'Cereals',
      durationDays: '80-100',
      durationCategory: 'medium',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '25-35°C',
      suitableStates: [
        'Maharashtra',
        'Karnataka',
        'Rajasthan',
        'Madhya Pradesh',
        'Tamil Nadu',
        'Andhra Pradesh',
        'Uttar Pradesh',
        'Gujarat'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '8-12 quintals',
      investmentPerAcre: '₹4,000-7,000',
      revenuePerAcre: '₹10,000-16,000',
      profitPerAcre: '₹4,000-9,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'September-October',
      description: 'Major dryland cereal crop'),
  const CropKnowledgeEntry(
      id: 'CR009',
      name: 'Foxtail Millet',
      variety: 'Co-5',
      category: 'Cereals',
      durationDays: '65-85',
      durationCategory: 'short',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Tamil Nadu',
        'Karnataka',
        'Andhra Pradesh',
        'Telangana',
        'Maharashtra'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '4-6 quintals',
      investmentPerAcre: '₹3,000-5,000',
      revenuePerAcre: '₹12,000-18,000',
      profitPerAcre: '₹7,000-13,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'August-September',
      description: 'Nutritious small millet, growing health food market'),
  const CropKnowledgeEntry(
      id: 'CR010',
      name: 'Little Millet',
      variety: 'VLM-401',
      category: 'Cereals',
      durationDays: '60-80',
      durationCategory: 'short',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Tamil Nadu',
        'Karnataka',
        'Andhra Pradesh',
        'Odisha',
        'Jharkhand',
        'Chhattisgarh'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '3-5 quintals',
      investmentPerAcre: '₹2,500-4,500',
      revenuePerAcre: '₹10,000-17,500',
      profitPerAcre: '₹6,000-13,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'August-September',
      description: 'Small millet with growing health food demand'),

  // PULSES
  const CropKnowledgeEntry(
      id: 'CR011',
      name: 'Green Gram (Moong)',
      variety: 'Pusa-1706',
      category: 'Pulses',
      durationDays: '55-70',
      durationCategory: 'short',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '25-35°C',
      suitableStates: [
        'Rajasthan',
        'Maharashtra',
        'Madhya Pradesh',
        'Andhra Pradesh',
        'Tamil Nadu',
        'Karnataka',
        'Uttar Pradesh',
        'Haryana',
        'Punjab'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '4-6 quintals',
      investmentPerAcre: '₹4,000-6,000',
      revenuePerAcre: '₹20,000-30,000',
      profitPerAcre: '₹14,000-24,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'July',
      harvestMonth: 'September-October',
      description: 'Short duration pulse, nitrogen fixing'),
  const CropKnowledgeEntry(
      id: 'CR012',
      name: 'Black Gram (Urad)',
      variety: 'TU-94-2',
      category: 'Pulses',
      durationDays: '60-80',
      durationCategory: 'short',
      suitableSoils: ['Clay', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '25-35°C',
      suitableStates: [
        'Madhya Pradesh',
        'Uttar Pradesh',
        'Rajasthan',
        'Tamil Nadu',
        'Andhra Pradesh',
        'Maharashtra'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '4-7 quintals',
      investmentPerAcre: '₹4,500-6,500',
      revenuePerAcre: '₹24,000-42,000',
      profitPerAcre: '₹18,000-35,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'July',
      harvestMonth: 'October',
      description: 'Important pulse crop, rich in protein'),
  const CropKnowledgeEntry(
      id: 'CR013',
      name: 'Chickpea (Chana)',
      variety: 'JG-74',
      category: 'Pulses',
      durationDays: '90-120',
      durationCategory: 'medium',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '15-30°C',
      suitableStates: [
        'Madhya Pradesh',
        'Rajasthan',
        'Maharashtra',
        'Andhra Pradesh',
        'Karnataka',
        'Uttar Pradesh',
        'Gujarat',
        'Punjab',
        'Haryana'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Rabi',
      expectedYieldPerAcre: '8-12 quintals',
      investmentPerAcre: '₹5,000-8,000',
      revenuePerAcre: '₹32,000-48,000',
      profitPerAcre: '₹24,000-40,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'October',
      harvestMonth: 'February-March',
      description: 'Major rabi pulse, highest production pulse'),
  const CropKnowledgeEntry(
      id: 'CR014',
      name: 'Pigeon Pea (Toor/Arhar)',
      variety: 'ICPH-2671',
      category: 'Pulses',
      durationDays: '120-180',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Maharashtra',
        'Karnataka',
        'Andhra Pradesh',
        'Madhya Pradesh',
        'Gujarat',
        'Rajasthan',
        'Tamil Nadu',
        'Uttar Pradesh'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '6-10 quintals',
      investmentPerAcre: '₹6,000-10,000',
      revenuePerAcre: '₹30,000-50,000',
      profitPerAcre: '₹20,000-40,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'January-March',
      description: 'Major pigeon pea variety, long duration'),

  // VEGETABLES - LEAFY
  const CropKnowledgeEntry(
      id: 'CR015',
      name: 'Coriander',
      variety: 'CO-1',
      category: 'Leafy Vegetables',
      durationDays: '30-45',
      durationCategory: 'short',
      suitableSoils: ['Loamy', 'Sandy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '15-30°C',
      suitableStates: [
        'Tamil Nadu',
        'Andhra Pradesh',
        'Karnataka',
        'Rajasthan',
        'Gujarat',
        'Maharashtra',
        'Madhya Pradesh',
        'Uttar Pradesh',
        'Punjab',
        'Haryana',
        'Bihar',
        'West Bengal',
        'Kerala',
        'Telangana',
        'Odisha',
        'Assam'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '4-6 quintals',
      investmentPerAcre: '₹8,000-12,000',
      revenuePerAcre: '₹32,000-48,000',
      profitPerAcre: '₹20,000-36,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'Throughout year',
      harvestMonth: '30-45 days after sowing',
      description: 'Widely used herb, leaves and seeds both valuable'),
  const CropKnowledgeEntry(
      id: 'CR016',
      name: 'Mint (Pudina)',
      variety: 'Local',
      category: 'Leafy Vegetables',
      durationDays: '25-35',
      durationCategory: 'short',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '20-35°C',
      suitableStates: ['All India'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '3-5 quintals',
      investmentPerAcre: '₹6,000-10,000',
      revenuePerAcre: '₹24,000-40,000',
      profitPerAcre: '₹16,000-30,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'Throughout year',
      harvestMonth: '25-35 days after planting',
      description: 'Fast growing aromatic herb, high demand'),
  const CropKnowledgeEntry(
      id: 'CR017',
      name: 'Spinach',
      variety: 'All Green',
      category: 'Leafy Vegetables',
      durationDays: '25-35',
      durationCategory: 'short',
      suitableSoils: ['Loamy', 'Sandy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '10-25°C',
      suitableStates: ['All India'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Rabi',
      expectedYieldPerAcre: '8-12 quintals',
      investmentPerAcre: '₹5,000-8,000',
      revenuePerAcre: '₹20,000-30,000',
      profitPerAcre: '₹12,000-22,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'October-November',
      harvestMonth: '30-40 days after sowing',
      description: 'Nutritious leafy green, quick returns'),

  // VEGETABLES - OTHER
  const CropKnowledgeEntry(
      id: 'CR018',
      name: 'Tomato',
      variety: 'Arka Rakshak',
      category: 'Vegetables',
      durationDays: '60-80',
      durationCategory: 'medium',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '20-30°C',
      suitableStates: ['All India'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '20-30 quintals',
      investmentPerAcre: '₹25,000-35,000',
      revenuePerAcre: '₹60,000-90,000',
      profitPerAcre: '₹30,000-55,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-July, January-February',
      harvestMonth: '90-120 days after transplanting',
      description: 'Major vegetable crop, high demand year-round'),
  const CropKnowledgeEntry(
      id: 'CR019',
      name: 'Brinjal',
      variety: 'Pusa Purple Long',
      category: 'Vegetables',
      durationDays: '60-80',
      durationCategory: 'medium',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '22-32°C',
      suitableStates: ['All India'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '15-25 quintals',
      investmentPerAcre: '₹15,000-25,000',
      revenuePerAcre: '₹45,000-75,000',
      profitPerAcre: '₹25,000-50,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July, January',
      harvestMonth: '80-100 days after transplanting',
      description: 'Popular solanaceous vegetable, long bearing'),
  const CropKnowledgeEntry(
      id: 'CR020',
      name: 'Chilli',
      variety: 'Byadgi',
      category: 'Vegetables',
      durationDays: '90-120',
      durationCategory: 'medium',
      suitableSoils: ['Loamy', 'Sandy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Andhra Pradesh',
        'Karnataka',
        'Tamil Nadu',
        'Maharashtra',
        'Rajasthan',
        'Madhya Pradesh',
        'West Bengal',
        'Odisha'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '8-15 quintals',
      investmentPerAcre: '₹18,000-28,000',
      revenuePerAcre: '₹64,000-120,000',
      profitPerAcre: '₹40,000-90,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'October-December',
      description: 'Important spice crop, wide variety of uses'),
  const CropKnowledgeEntry(
      id: 'CR021',
      name: 'Okra (Lady Finger)',
      variety: 'Pusa Bhairav',
      category: 'Vegetables',
      durationDays: '50-65',
      durationCategory: 'short',
      suitableSoils: ['Loamy', 'Sandy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '25-35°C',
      suitableStates: ['All India'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '8-12 quintals',
      investmentPerAcre: '₹10,000-15,000',
      revenuePerAcre: '₹24,000-36,000',
      profitPerAcre: '₹12,000-21,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: '50-65 days after sowing',
      description: 'Popular warm season vegetable'),
  const CropKnowledgeEntry(
      id: 'CR022',
      name: 'Onion',
      variety: 'Bhima Red',
      category: 'Vegetables',
      durationDays: '80-120',
      durationCategory: 'medium',
      suitableSoils: ['Loamy', 'Sandy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '15-30°C',
      suitableStates: [
        'Maharashtra',
        'Karnataka',
        'Tamil Nadu',
        'Andhra Pradesh',
        'Rajasthan',
        'Madhya Pradesh',
        'Gujarat',
        'Bihar'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Rabi',
      expectedYieldPerAcre: '15-25 quintals',
      investmentPerAcre: '₹15,000-25,000',
      revenuePerAcre: '₹60,000-100,000',
      profitPerAcre: '₹40,000-75,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'October-November',
      harvestMonth: 'February-March',
      description: 'Essential kitchen vegetable, good storage crop'),
  const CropKnowledgeEntry(
      id: 'CR023',
      name: 'Potato',
      variety: 'Kufri Jyoti',
      category: 'Vegetables',
      durationDays: '70-90',
      durationCategory: 'medium',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '15-25°C',
      suitableStates: [
        'Uttar Pradesh',
        'West Bengal',
        'Bihar',
        'Punjab',
        'Haryana',
        'Gujarat',
        'Madhya Pradesh'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Rabi',
      expectedYieldPerAcre: '80-120 quintals',
      investmentPerAcre: '₹25,000-35,000',
      revenuePerAcre: '₹60,000-96,000',
      profitPerAcre: '₹25,000-61,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'October-November',
      harvestMonth: 'January-March',
      description: 'Major tuber crop, high yield per acre'),

  // FRUITS
  const CropKnowledgeEntry(
      id: 'CR024',
      name: 'Mango',
      variety: 'Alphonso',
      category: 'Fruits',
      durationDays: '120-150',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '24-38°C',
      suitableStates: [
        'Maharashtra',
        'Andhra Pradesh',
        'Tamil Nadu',
        'Karnataka',
        'Gujarat',
        'Uttar Pradesh',
        'Bihar',
        'West Bengal',
        'Rajasthan',
        'Kerala'
      ],
      suitableDistricts: ['Ratnagiri', 'Devgad', 'All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '5-10 tonnes',
      investmentPerAcre: '₹50,000-100,000',
      revenuePerAcre: '₹200,000-500,000',
      profitPerAcre: '₹150,000-400,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-August (rainy)',
      harvestMonth: 'March-June',
      description: 'King of fruits, India is largest producer'),
  const CropKnowledgeEntry(
      id: 'CR025',
      name: 'Banana',
      variety: 'Grand Naine (Robusta)',
      category: 'Fruits',
      durationDays: '11-14 months',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'High',
      suitableTemperature: '25-35°C',
      suitableStates: [
        'Tamil Nadu',
        'Maharashtra',
        'Andhra Pradesh',
        'Karnataka',
        'Kerala',
        'Gujarat',
        'Madhya Pradesh',
        'Bihar',
        'West Bengal'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '15-25 tonnes',
      investmentPerAcre: '₹40,000-60,000',
      revenuePerAcre: '₹150,000-250,000',
      profitPerAcre: '₹100,000-190,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'Throughout year',
      harvestMonth: '11-14 months after planting',
      description: 'Major fruit crop, quick returns'),
  const CropKnowledgeEntry(
      id: 'CR026',
      name: 'Coconut',
      variety: 'West Coast Tall',
      category: 'Plantation Crops',
      durationDays: '60-72 months',
      durationCategory: 'long',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Kerala',
        'Karnataka',
        'Tamil Nadu',
        'Andhra Pradesh',
        'Goa',
        'West Bengal',
        'Odisha'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '80-100 nuts/tree/year',
      investmentPerAcre: '₹30,000-50,000',
      revenuePerAcre: '₹80,000-120,000',
      profitPerAcre: '₹40,000-70,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-September',
      harvestMonth: 'Year-round after maturity',
      description: 'Important plantation crop, multiple uses'),
  const CropKnowledgeEntry(
      id: 'CR027',
      name: 'Papaya',
      variety: 'Pusa Delicious',
      category: 'Fruits',
      durationDays: '6-8 months',
      durationCategory: 'medium',
      suitableSoils: ['Loamy', 'Sandy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '25-35°C',
      suitableStates: ['All India'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '15-25 tonnes',
      investmentPerAcre: '₹20,000-30,000',
      revenuePerAcre: '₹60,000-100,000',
      profitPerAcre: '₹35,000-70,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'Throughout year',
      harvestMonth: '6-8 months after planting',
      description: 'Fast growing fruit, early returns'),
  const CropKnowledgeEntry(
      id: 'CR028',
      name: 'Grapes',
      variety: 'Thompson Seedless',
      category: 'Fruits',
      durationDays: '120-150',
      durationCategory: 'long',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '15-35°C',
      suitableStates: [
        'Maharashtra',
        'Andhra Pradesh',
        'Karnataka',
        'Tamil Nadu',
        'Rajasthan'
      ],
      suitableDistricts: ['Nashik', 'Pune', 'All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '8-15 tonnes',
      investmentPerAcre: '₹80,000-150,000',
      revenuePerAcre: '₹200,000-400,000',
      profitPerAcre: '₹100,000-250,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'January-February',
      harvestMonth: 'April-May',
      description: 'High value fruit, good export potential'),

  // SPICES
  const CropKnowledgeEntry(
      id: 'CR029',
      name: 'Turmeric',
      variety: 'Erode',
      category: 'Spices',
      durationDays: '240-270',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Tamil Nadu',
        'Andhra Pradesh',
        'Maharashtra',
        'Karnataka',
        'Kerala',
        'Odisha',
        'West Bengal',
        'Assam'
      ],
      suitableDistricts: ['Erode', 'Salem', 'All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '15-25 quintals',
      investmentPerAcre: '₹25,000-40,000',
      revenuePerAcre: '₹100,000-175,000',
      profitPerAcre: '₹70,000-135,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'May-June',
      harvestMonth: 'January-February',
      description: 'Golden spice, high export demand'),
  const CropKnowledgeEntry(
      id: 'CR030',
      name: 'Black Pepper',
      variety: 'Panniyur-1',
      category: 'Spices',
      durationDays: '240-300',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Kerala',
        'Karnataka',
        'Tamil Nadu',
        'Andhra Pradesh',
        'Goa'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '2-3 quintals dried',
      investmentPerAcre: '₹40,000-60,000',
      revenuePerAcre: '₹100,000-180,000',
      profitPerAcre: '₹50,000-120,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'November-January',
      description: 'King of spices, climbing vine'),
  const CropKnowledgeEntry(
      id: 'CR031',
      name: 'Cardamom',
      variety: 'Malabar Large',
      category: 'Spices',
      durationDays: '240-300',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '10-35°C',
      suitableStates: ['Kerala', 'Karnataka', 'Tamil Nadu'],
      suitableDistricts: ['Idukki', 'Wayanad', 'All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '1-2 quintals',
      investmentPerAcre: '₹60,000-100,000',
      revenuePerAcre: '₹200,000-400,000',
      profitPerAcre: '₹130,000-300,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'October-February',
      description: 'Queen of spices, high value'),

  // OILSEEDS
  const CropKnowledgeEntry(
      id: 'CR032',
      name: 'Groundnut',
      variety: 'TAG-24',
      category: 'Oilseeds',
      durationDays: '90-120',
      durationCategory: 'medium',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '25-35°C',
      suitableStates: [
        'Gujarat',
        'Rajasthan',
        'Andhra Pradesh',
        'Tamil Nadu',
        'Karnataka',
        'Maharashtra',
        'Madhya Pradesh'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '8-12 quintals',
      investmentPerAcre: '₹8,000-12,000',
      revenuePerAcre: '₹32,000-48,000',
      profitPerAcre: '₹20,000-36,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'October-November',
      description: 'Important oilseed crop'),
  const CropKnowledgeEntry(
      id: 'CR033',
      name: 'Sesame (Til)',
      variety: 'GT-10',
      category: 'Oilseeds',
      durationDays: '75-90',
      durationCategory: 'short',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '25-35°C',
      suitableStates: [
        'Rajasthan',
        'Gujarat',
        'Uttar Pradesh',
        'Madhya Pradesh',
        'Andhra Pradesh',
        'Tamil Nadu'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Kharif',
      expectedYieldPerAcre: '3-5 quintals',
      investmentPerAcre: '₹3,000-5,000',
      revenuePerAcre: '₹15,000-25,000',
      profitPerAcre: '₹10,000-20,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'September-October',
      description: 'Minor oilseed, nutritious'),
  const CropKnowledgeEntry(
      id: 'CR034',
      name: 'Mustard',
      variety: 'RH-06',
      category: 'Oilseeds',
      durationDays: '100-130',
      durationCategory: 'medium',
      suitableSoils: ['Loamy', 'Sandy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '10-25°C',
      suitableStates: [
        'Rajasthan',
        'Haryana',
        'Punjab',
        'Madhya Pradesh',
        'Uttar Pradesh',
        'Gujarat',
        'Bihar'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Rabi',
      expectedYieldPerAcre: '6-10 quintals',
      investmentPerAcre: '₹5,000-8,000',
      revenuePerAcre: '₹24,000-40,000',
      profitPerAcre: '₹16,000-32,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'October',
      harvestMonth: 'February-March',
      description: 'Major rabi oilseed crop'),

  // FLOWERS
  const CropKnowledgeEntry(
      id: 'CR035',
      name: 'Marigold',
      variety: 'Pusa Narangi Gainda',
      category: 'Flowers',
      durationDays: '50-60',
      durationCategory: 'short',
      suitableSoils: ['Loamy', 'Sandy', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '20-35°C',
      suitableStates: ['All India'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '8-12 tonnes fresh',
      investmentPerAcre: '₹20,000-30,000',
      revenuePerAcre: '₹80,000-120,000',
      profitPerAcre: '₹50,000-90,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'Throughout year',
      harvestMonth: '50-60 days after sowing',
      description: 'Popular flower, religious and decorative use'),
  const CropKnowledgeEntry(
      id: 'CR036',
      name: 'Jasmine',
      variety: 'Mysore Mallige',
      category: 'Flowers',
      durationDays: '120-150',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Tamil Nadu',
        'Karnataka',
        'Kerala',
        'Andhra Pradesh',
        'Maharashtra'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '5-8 tonnes',
      investmentPerAcre: '₹30,000-50,000',
      revenuePerAcre: '₹150,000-250,000',
      profitPerAcre: '₹100,000-200,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-July',
      harvestMonth: 'Year-round after establishment',
      description: 'Premium fragrant flower, high value'),
  const CropKnowledgeEntry(
      id: 'CR037',
      name: 'Rose',
      variety: 'Madam Red',
      category: 'Flowers',
      durationDays: '120-150',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'Medium',
      suitableTemperature: '15-30°C',
      suitableStates: [
        'Karnataka',
        'Tamil Nadu',
        'Maharashtra',
        'Andhra Pradesh',
        'Rajasthan'
      ],
      suitableDistricts: ['Bangalore', 'All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '2-3 lakh stems',
      investmentPerAcre: '₹50,000-80,000',
      revenuePerAcre: '₹200,000-400,000',
      profitPerAcre: '₹100,000-300,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'January-February, June-July',
      harvestMonth: 'Year-round after establishment',
      description: 'Major cut flower, export potential'),

  // PLANTATION CROPS
  const CropKnowledgeEntry(
      id: 'CR038',
      name: 'Tea',
      variety: 'TRFK-306',
      category: 'Plantation Crops',
      durationDays: 'Perennial',
      durationCategory: 'long',
      suitableSoils: ['Loamy', 'Clay', 'All'],
      waterRequirement: 'High',
      suitableTemperature: '10-30°C',
      suitableStates: [
        'Assam',
        'West Bengal',
        'Tamil Nadu',
        'Kerala',
        'Karnataka'
      ],
      suitableDistricts: ['Darjeeling', 'All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '800-1200 kg',
      investmentPerAcre: '₹40,000-60,000',
      revenuePerAcre: '₹160,000-240,000',
      profitPerAcre: '₹100,000-180,000',
      marketDemand: 'High',
      riskLevel: 'Medium',
      bestPlantingMonth: 'June-August',
      harvestMonth: 'Year-round after 3 years',
      description: 'Major beverage crop, export commodity'),

  // TREE CROPS
  const CropKnowledgeEntry(
      id: 'CR039',
      name: 'Drumstick',
      variety: 'PKM-1',
      category: 'Tree Crops',
      durationDays: 'Perennial',
      durationCategory: 'long',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '20-40°C',
      suitableStates: [
        'Tamil Nadu',
        'Andhra Pradesh',
        'Karnataka',
        'Maharashtra',
        'Madhya Pradesh',
        'Rajasthan'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '100-200 kg pods',
      investmentPerAcre: '₹10,000-15,000',
      revenuePerAcre: '₹30,000-60,000',
      profitPerAcre: '₹18,000-45,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: '6-8 months after planting',
      description: 'Multipurpose tree, edible pods and leaves'),
  const CropKnowledgeEntry(
      id: 'CR040',
      name: 'Neem',
      variety: 'Local',
      category: 'Tree Crops',
      durationDays: 'Perennial',
      durationCategory: 'long',
      suitableSoils: ['Sandy', 'Loamy', 'Clay', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '20-40°C',
      suitableStates: ['All India'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '50-100 kg seeds',
      investmentPerAcre: '₹5,000-8,000',
      revenuePerAcre: '₹15,000-30,000',
      profitPerAcre: '₹8,000-22,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'June-July',
      harvestMonth: '2-3 years for seeds',
      description: 'Medicinal tree, biopesticide source'),

  // MEDICINAL / AROMATIC
  const CropKnowledgeEntry(
      id: 'CR041',
      name: 'Aloe Vera',
      variety: 'Ghatikaran',
      category: 'Medicinal/Aromatic',
      durationDays: '120-150',
      durationCategory: 'long',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '20-40°C',
      suitableStates: [
        'Rajasthan',
        'Gujarat',
        'Maharashtra',
        'Madhya Pradesh',
        'Tamil Nadu',
        'Andhra Pradesh'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '12-15 tonnes',
      investmentPerAcre: '₹15,000-20,000',
      revenuePerAcre: '₹60,000-75,000',
      profitPerAcre: '₹40,000-55,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'March-April',
      harvestMonth: '12 months after planting',
      description: 'Medicinal and cosmetic use, drought tolerant'),
  const CropKnowledgeEntry(
      id: 'CR042',
      name: 'Ashwagandha',
      variety: 'Jeevani',
      category: 'Medicinal/Aromatic',
      durationDays: '120-180',
      durationCategory: 'long',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '20-35°C',
      suitableStates: [
        'Rajasthan',
        'Madhya Pradesh',
        'Maharashtra',
        'Gujarat',
        'Andhra Pradesh',
        'Tamil Nadu'
      ],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'Rabi',
      expectedYieldPerAcre: '4-6 quintals roots',
      investmentPerAcre: '₹8,000-12,000',
      revenuePerAcre: '₹40,000-60,000',
      profitPerAcre: '₹28,000-48,000',
      marketDemand: 'High',
      riskLevel: 'Low',
      bestPlantingMonth: 'July-October',
      harvestMonth: 'January-March',
      description: 'Important medicinal herb, growing global demand'),
  const CropKnowledgeEntry(
      id: 'CR043',
      name: 'Lemongrass',
      variety: 'OD-19',
      category: 'Medicinal/Aromatic',
      durationDays: '75-90',
      durationCategory: 'short',
      suitableSoils: ['Sandy', 'Loamy', 'All'],
      waterRequirement: 'Low',
      suitableTemperature: '20-40°C',
      suitableStates: ['All India'],
      suitableDistricts: ['All'],
      agroClimaticZones: 'All',
      season: 'All',
      expectedYieldPerAcre: '100-150 kg oil',
      investmentPerAcre: '₹10,000-15,000',
      revenuePerAcre: '₹50,000-75,000',
      profitPerAcre: '₹35,000-60,000',
      marketDemand: 'Medium',
      riskLevel: 'Low',
      bestPlantingMonth: 'February-March',
      harvestMonth: '3-4 cuttings per year',
      description: 'Aromatic grass, essential oil crop'),
];
