/**
 * VidhAI crop knowledge dataset.
 *
 * Publicly documented, government-sourced agronomic reference data
 * (Package of Practices, Season & Crop Reports, ICAR / State Agriculture
 * Dept publications). Values are national/state reference estimates and are
 * surfaced in the app with clear "Estimate" labels — never presented as live
 * or farm-specific figures.
 */

export type WaterRequirement = 'Low' | 'Medium' | 'High';
export type DemandLevel = 'High' | 'Medium' | 'Low';
export type RiskLevel = 'Low' | 'Medium' | 'High';

export type TaskType =
  | 'land'
  | 'planting'
  | 'water'
  | 'nutrition'
  | 'weed'
  | 'pest'
  | 'harvest'
  | 'monitor';

export interface CropTaskTemplate {
  task: string;
  type: TaskType;
  priority: 'high' | 'medium' | 'low';
}

export interface CropStageTemplate {
  name: string;
  dayStartPct: number;
  dayEndPct: number;
  activities: CropTaskTemplate[];
}

export interface CropKnowledgeEntry {
  id: string;
  name: string;
  category: string;
  varieties: string[];
  season: string;
  durationDaysMin: number;
  durationDaysMax: number;
  soilTypes: string[];
  waterRequirement: WaterRequirement;
  temperatureMin: number;
  temperatureMax: number;
  states: string[];
  seedRatePerAcre: string;
  seedCostPerAcre: { min: number; max: number };
  cultivationCostPerAcre: { min: number; max: number };
  expectedYieldPerAcre: { min: number; max: number; unit: string };
  pricePerQuintal: { min: number; max: number };
  plantingWindows: string[];
  harvestMonths: string;
  risks: string[];
  commonPests: string[];
  commonDiseases: string[];
  marketDemand: DemandLevel;
  riskLevel: RiskLevel;
  description: string;
  stageTemplates: CropStageTemplate[];
  cropRotationNotes?: string;
  fallowSuitable?: boolean;
  organicFriendly?: boolean;
}

function stages(opts?: {
  germ?: [number, number];
  veg?: [number, number];
  flower?: [number, number];
}): CropStageTemplate[] {
  const germ = opts?.germ ?? [5, 15];
  const veg = opts?.veg ?? [15, 55];
  const flower = opts?.flower ?? [55, 80];
  return [
    {
      name: 'Land Preparation',
      dayStartPct: 0,
      dayEndPct: 5,
      activities: [
        { task: 'Prepare the field and level the soil', type: 'land', priority: 'high' },
      ],
    },
    {
      name: 'Sowing / Planting',
      dayStartPct: 0,
      dayEndPct: 10,
      activities: [
        { task: 'Sow or transplant at recommended spacing', type: 'planting', priority: 'high' },
        { task: 'Apply basal fertilizer at sowing time', type: 'nutrition', priority: 'high' },
      ],
    },
    {
      name: 'Germination / Establishment',
      dayStartPct: germ[0],
      dayEndPct: germ[1],
      activities: [
        { task: 'Irrigate regularly for seedling establishment', type: 'water', priority: 'high' },
      ],
    },
    {
      name: 'Vegetative Growth',
      dayStartPct: veg[0],
      dayEndPct: veg[1],
      activities: [
        { task: 'Apply top dressing (urea / DAP) as needed', type: 'nutrition', priority: 'medium' },
        { task: 'Carry out weeding / weed control', type: 'weed', priority: 'medium' },
        { task: 'Maintain irrigation schedule', type: 'water', priority: 'medium' },
      ],
    },
    {
      name: 'Critical / Flowering Stage',
      dayStartPct: flower[0],
      dayEndPct: flower[1],
      activities: [
        { task: 'Monitor for pests and diseases', type: 'pest', priority: 'high' },
        { task: 'Ensure adequate water at the critical stage', type: 'water', priority: 'high' },
        { task: 'Scout the crop twice a week', type: 'monitor', priority: 'medium' },
      ],
    },
    {
      name: 'Maturity',
      dayStartPct: flower[1],
      dayEndPct: 95,
      activities: [
        { task: 'Reduce irrigation as the crop matures', type: 'water', priority: 'low' },
      ],
    },
    {
      name: 'Harvest',
      dayStartPct: 90,
      dayEndPct: 100,
      activities: [
        { task: 'Harvest at optimum maturity', type: 'harvest', priority: 'high' },
        { task: 'Thresh and dry produce properly', type: 'harvest', priority: 'medium' },
      ],
    },
  ];
}

export const CROP_DATA_VERSION = 1;

/**
 * Large internal crop pool (60+ crops across categories). The app always
 * evaluates a subset of this pool for the farmer's state/season and returns
 * exactly 10 ranked recommendations.
 */
export const CROP_KNOWLEDGE: CropKnowledgeEntry[] = [
  {
    id: 'rice',
    name: 'Rice',
    category: 'Cereals',
    varieties: ['BPT 5204', 'MTU 7029', 'Jaya', 'IR 64', 'Pusa Basmati 1121', 'Swarna'],
    season: 'Kharif/Rabi',
    durationDaysMin: 120,
    durationDaysMax: 160,
    soilTypes: ['Clayey', 'Clay Loam', 'Alluvial', 'Loamy'],
    waterRequirement: 'High',
    temperatureMin: 20,
    temperatureMax: 38,
    states: ['Andhra Pradesh', 'Telangana', 'Punjab', 'Haryana', 'Uttar Pradesh', 'West Bengal', 'Odisha', 'Bihar', 'Chhattisgarh', 'Tamil Nadu', 'Karnataka', 'Assam', 'Madhya Pradesh', 'Jharkhand'],
    seedRatePerAcre: '40–60 kg (transplanted) / 80–100 kg (direct seeded)',
    seedCostPerAcre: { min: 1200, max: 3200 },
    cultivationCostPerAcre: { min: 18000, max: 32000 },
    expectedYieldPerAcre: { min: 24, max: 40, unit: 'quintals/acre' },
    pricePerQuintal: { min: 2180, max: 3100 },
    plantingWindows: ['Kharif: May–July', 'Rabi: Nov–Dec'],
    harvestMonths: 'Oct–Dec (Kharif), Mar–Apr (Rabi)',
    risks: ['Heavy dependence on assured water', 'Labour intensive', 'Price varies with MSP revisions', 'Susceptible to blast and stem borer'],
    commonPests: ['Stem borer', 'Brown plant hopper', 'Leaf folder'],
    commonDiseases: ['Blast', 'Bacterial leaf blight', 'Sheath blight'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Staple cereal grown extensively across India. High water need; suited to irrigated and rainfed lowland conditions. Minimum Support Price provides a price floor.',
    stageTemplates: stages({ germ: [10, 25], veg: [20, 55], flower: [55, 80] }),
    cropRotationNotes: 'Rotate with pulses or oilseeds to improve soil nitrogen.',
    organicFriendly: false,
  },
  {
    id: 'wheat',
    name: 'Wheat',
    category: 'Cereals',
    varieties: ['HD 2967', 'HD 3086', 'PBW 343', 'GW 322', 'GW 496'],
    season: 'Rabi',
    durationDaysMin: 110,
    durationDaysMax: 150,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial', 'Clay Loam'],
    waterRequirement: 'Medium',
    temperatureMin: 10,
    temperatureMax: 30,
    states: ['Uttar Pradesh', 'Punjab', 'Haryana', 'Madhya Pradesh', 'Rajasthan', 'Bihar', 'Gujarat', 'Maharashtra', 'West Bengal'],
    seedRatePerAcre: '100–125 kg',
    seedCostPerAcre: { min: 2200, max: 3500 },
    cultivationCostPerAcre: { min: 15000, max: 25000 },
    expectedYieldPerAcre: { min: 32, max: 50, unit: 'quintals/acre' },
    pricePerQuintal: { min: 2275, max: 2500 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Mar–Apr',
    risks: ['Terminal heat stress during grain filling', 'Needs cold winter nights', 'Irrigation gap at crown-root initiation'],
    commonPests: ['Aphids', 'Termites', 'Heat'],
    commonDiseases: ['Yellow rust', 'Brown rust', 'Loose smut'],
    marketDemand: 'High',
    riskLevel: 'Low',
    description: 'Main rabi cereal. Cool-season crop well suited to Indo-Gangetic plains; MSP-backed. Sensitive to heat after March.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 50], flower: [50, 75] }),
    cropRotationNotes: 'Excellent rotation with rice, jute, sugarcane.',
    organicFriendly: true,
  },
  {
    id: 'maize',
    name: 'Maize',
    category: 'Cereals',
    varieties: ['DKC 9178', 'PMH 1', 'PEHM 2', 'African Tall (fodder)'],
    season: 'Kharif/Rabi',
    durationDaysMin: 90,
    durationDaysMax: 120,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial', 'Clay Loam', 'Red Loamy'],
    waterRequirement: 'Medium',
    temperatureMin: 20,
    temperatureMax: 35,
    states: ['Karnataka', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Bihar', 'Rajasthan', 'Uttar Pradesh', 'Maharashtra', 'Tamil Nadu'],
    seedRatePerAcre: '8–12 kg',
    seedCostPerAcre: { min: 2000, max: 4200 },
    cultivationCostPerAcre: { min: 14000, max: 22000 },
    expectedYieldPerAcre: { min: 24, max: 38, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1900, max: 2400 },
    plantingWindows: ['Kharif: May–Jun', 'Rabi: Sep–Oct'],
    harvestMonths: 'Aug–Oct (Kharif), Jan–Feb (Rabi)',
    risks: ['Fall armyworm damage', 'Needs rain or irrigation at flowering', 'Price volatility for non-MSP markets'],
    commonPests: ['Fall armyworm', 'Stem borer'],
    commonDiseases: ['Turcicum blight', 'Common rust'],
    marketDemand: 'Medium',
    riskLevel: 'Medium',
    description: 'Versatile crop for grain, fodder and industrial use. Short duration and high biomass; good for crop rotation.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 50], flower: [50, 75] }),
    cropRotationNotes: 'Good with pulses; pigeonpea intercropping reduces risk.',
    fallowSuitable: true,
    organicFriendly: true,
  },
  {
    id: 'bajra',
    name: 'Pearl Millet (Bajra)',
    category: 'Cereals',
    varieties: ['HHB 197', 'GHB 744', 'MP 776', 'ICMH 356'],
    season: 'Kharif',
    durationDaysMin: 80,
    durationDaysMax: 100,
    soilTypes: ['Sandy', 'Sandy Loam', 'Loamy'],
    waterRequirement: 'Low',
    temperatureMin: 24,
    temperatureMax: 40,
    states: ['Rajasthan', 'Haryana', 'Gujarat', 'Uttar Pradesh', 'Maharashtra', 'Karnataka', 'Madhya Pradesh', 'Tamil Nadu'],
    seedRatePerAcre: '3–4 kg',
    seedCostPerAcre: { min: 700, max: 1500 },
    cultivationCostPerAcre: { min: 9000, max: 16000 },
    expectedYieldPerAcre: { min: 14, max: 22, unit: 'quintals/acre' },
    pricePerQuintal: { min: 2200, max: 2800 },
    plantingWindows: ['Kharif: Jun–Jul'],
    harvestMonths: 'Aug–Oct',
    risks: ['Bird damage near maturity', 'Ergot in humid areas', 'Downy mildew in rainy moisture'],
    commonPests: ['Shoot fly', 'White grub'],
    commonDiseases: ['Downy mildew', 'Ergot', 'Smut'],
    marketDemand: 'Medium',
    riskLevel: 'Low',
    description: 'Drought-tolerant coarse cereal ideal for dry, sandy tracts. Matures quickly and tolerates heat well.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 80] }),
    cropRotationNotes: 'Good rotation partner for pulses and groundnut.',
    fallowSuitable: true,
    organicFriendly: true,
  },
  {
    id: 'sorghum',
    name: 'Sorghum (Jowar)',
    category: 'Cereals',
    varieties: ['CSV 33', 'CSV 23', 'M 35-1', 'SSV 84'],
    season: 'Kharif/Rabi',
    durationDaysMin: 90,
    durationDaysMax: 120,
    soilTypes: ['Sandy Loam', 'Loamy', 'Black Cotton', 'Red Loamy'],
    waterRequirement: 'Low',
    temperatureMin: 20,
    temperatureMax: 38,
    states: ['Maharashtra', 'Karnataka', 'Telangana', 'Andhra Pradesh', 'Tamil Nadu', 'Madhya Pradesh', 'Gujarat', 'Rajasthan'],
    seedRatePerAcre: '8–10 kg',
    seedCostPerAcre: { min: 900, max: 1800 },
    cultivationCostPerAcre: { min: 9000, max: 15000 },
    expectedYieldPerAcre: { min: 12, max: 20, unit: 'quintals/acre' },
    pricePerQuintal: { min: 2100, max: 2600 },
    plantingWindows: ['Kharif: Jun–Jul', 'Rabi: Sep–Oct'],
    harvestMonths: 'Sep–Nov (Kharif), Jan–Mar (Rabi)',
    risks: ['Shoot fly early infestation', 'Stem borer', 'Less remunerative in glut years'],
    commonPests: ['Shoot fly', 'Stem borer', 'Aphids'],
    commonDiseases: ['Grain smut', 'Anthracnose'],
    marketDemand: 'Medium',
    riskLevel: 'Medium',
    description: 'Dryland cereal and fodder crop adapted to low rainfall. Naturally organic-friendly due to low input needs.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 80] }),
    organicFriendly: true,
    fallowSuitable: true,
  },
  {
    id: 'ragi',
    name: 'Finger Millet (Ragi)',
    category: 'Cereals',
    varieties: ['Indaf 9', 'GPU 28', 'KMR 301', 'PR 202'],
    season: 'Kharif/Rabi',
    durationDaysMin: 90,
    durationDaysMax: 120,
    soilTypes: ['Red Loamy', 'Sandy Loam', 'Loamy', 'Laterite'],
    waterRequirement: 'Low',
    temperatureMin: 18,
    temperatureMax: 32,
    states: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh', 'Telangana', 'Maharashtra', 'Odisha', 'Uttarakhand'],
    seedRatePerAcre: '4–6 kg',
    seedCostPerAcre: { min: 800, max: 1600 },
    cultivationCostPerAcre: { min: 9000, max: 15000 },
    expectedYieldPerAcre: { min: 16, max: 26, unit: 'quintals/acre' },
    pricePerQuintal: { min: 3000, max: 4200 },
    plantingWindows: ['Kharif: May–Jul', 'Rabi: Sep–Oct'],
    harvestMonths: 'Aug–Oct',
    risks: ['Blast under humid conditions', 'Needs careful water management', 'Small-grain harvesting labour'],
    commonPests: ['Pinky borer', 'Aphids'],
    commonDiseases: ['Blast', 'Leaf blight'],
    marketDemand: 'Medium',
    riskLevel: 'Low',
    description: 'Nutritious millet grown in rainfed conditions. Hardy, low-input and suited to laterite/red soils.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 80] }),
    organicFriendly: true,
    fallowSuitable: true,
  },
  {
    id: 'barley',
    name: 'Barley',
    category: 'Cereals',
    varieties: ['BH 959', 'BH 885', 'RD 2786', 'DWRB 101'],
    season: 'Rabi',
    durationDaysMin: 100,
    durationDaysMax: 125,
    soilTypes: ['Sandy Loam', 'Loamy', 'Alluvial'],
    waterRequirement: 'Low',
    temperatureMin: 10,
    temperatureMax: 25,
    states: ['Rajasthan', 'Uttar Pradesh', 'Madhya Pradesh', 'Haryana', 'Punjab', 'Bihar'],
    seedRatePerAcre: '80–100 kg',
    seedCostPerAcre: { min: 1600, max: 2400 },
    cultivationCostPerAcre: { min: 9000, max: 15000 },
    expectedYieldPerAcre: { min: 28, max: 45, unit: 'quintals/acre' },
    pricePerQuintal: { min: 2000, max: 2400 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Mar–Apr',
    risks: ['Limited industrial demand in some regions', 'Lodging with excess nitrogen'],
    commonPests: ['Aphids', 'Termites'],
    commonDiseases: ['Leaf rust', 'Net blotch'],
    marketDemand: 'Low',
    riskLevel: 'Low',
    description: 'Salt and drought tolerant cereal for marginal soils; used for malt and feed.',
    stageTemplates: stages(),
    fallowSuitable: true,
    organicFriendly: true,
  },
  {
    id: 'oats',
    name: 'Oats',
    category: 'Cereals',
    varieties: ['OS 6', 'Kent', 'Palampur'],
    season: 'Rabi',
    durationDaysMin: 90,
    durationDaysMax: 120,
    soilTypes: ['Loamy', 'Sandy Loam', 'Clay Loam'],
    waterRequirement: 'Medium',
    temperatureMin: 5,
    temperatureMax: 30,
    states: ['Punjab', 'Haryana', 'Uttar Pradesh', 'Madhya Pradesh', 'Rajasthan', 'Maharashtra'],
    seedRatePerAcre: '35–50 kg (grain), 80–100 kg (fodder)',
    seedCostPerAcre: { min: 2500, max: 4000 },
    cultivationCostPerAcre: { min: 9000, max: 16000 },
    expectedYieldPerAcre: { min: 22, max: 36, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1800, max: 2200 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Mar–Apr',
    risks: ['Small market for grain', 'Aphid damage'],
    commonPests: ['Aphids'],
    commonDiseases: ['Rust', 'Loose smut'],
    marketDemand: 'Low',
    riskLevel: 'Low',
    description: 'Grain and fodder crop; valuable in dairy-belt rotations.',
    stageTemplates: stages(),
    fallowSuitable: true,
    organicFriendly: true,
  },
  {
    id: 'chickpea',
    name: 'Chickpea (Gram)',
    category: 'Pulses',
    varieties: ['JG 315', 'JAKI 9218', 'JGK 3', 'IPCK 2004-29', 'PBG 5'],
    season: 'Rabi',
    durationDaysMin: 90,
    durationDaysMax: 120,
    soilTypes: ['Black Cotton', 'Loamy', 'Sandy Loam', 'Clay Loam'],
    waterRequirement: 'Low',
    temperatureMin: 15,
    temperatureMax: 30,
    states: ['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Karnataka', 'Telangana', 'Uttar Pradesh', 'Andhra Pradesh', 'Chhattisgarh'],
    seedRatePerAcre: '30–40 kg',
    seedCostPerAcre: { min: 2400, max: 4000 },
    cultivationCostPerAcre: { min: 9000, max: 15000 },
    expectedYieldPerAcre: { min: 10, max: 16, unit: 'quintals/acre' },
    pricePerQuintal: { min: 5200, max: 7000 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Feb–Mar',
    risks: ['Pod borer', 'Terminal drought if pods face heat', 'Fusarium wilt in warm soils'],
    commonPests: ['Gram pod borer', 'Aphids'],
    commonDiseases: ['Fusarium wilt', 'Dry root rot', 'Ascochyta blight'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Major rabi pulse, fixes atmospheric nitrogen. Rising domestic demand keeps prices firm.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 50], flower: [50, 75] }),
    cropRotationNotes: 'Classic rotation with wheat/maize improves soil fertility.',
    organicFriendly: true,
    fallowSuitable: true,
  },
  {
    id: 'pigeonpea',
    name: 'Pigeonpea (Arhar/Toor)',
    category: 'Pulses',
    varieties: ['Asha (ICPL 87119)', 'MAL 13', 'GT 101', 'PKV Tara', 'WRS 1'],
    season: 'Kharif',
    durationDaysMin: 150,
    durationDaysMax: 200,
    soilTypes: ['Loamy', 'Sandy Loam', 'Clay Loam', 'Red Loamy'],
    waterRequirement: 'Low',
    temperatureMin: 18,
    temperatureMax: 35,
    states: ['Maharashtra', 'Karnataka', 'Madhya Pradesh', 'Uttar Pradesh', 'Telangana', 'Andhra Pradesh', 'Gujarat', 'Rajasthan'],
    seedRatePerAcre: '8–10 kg (sole)',
    seedCostPerAcre: { min: 1800, max: 2800 },
    cultivationCostPerAcre: { min: 9000, max: 16000 },
    expectedYieldPerAcre: { min: 8, max: 14, unit: 'quintals/acre' },
    pricePerQuintal: { min: 8000, max: 11000 },
    plantingWindows: ['Kharif: May–Jun'],
    harvestMonths: 'Dec–Jan',
    risks: ['Prolonged drought in flowering', 'Pod borer pressure', 'Long duration keeps soil occupied'],
    commonPests: ['Pod borer', 'Pod fly'],
    commonDiseases: ['Fusarium wilt', 'Sterility mosaic'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'High-value long-duration pulse; excellent nitrogen fixer. Often intercropped with cereals.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 45], flower: [45, 75] }),
    cropRotationNotes: 'Intercrop with maize/pigeonpea for risk spreading.',
    organicFriendly: true,
  },
  {
    id: 'greengram',
    name: 'Green Gram (Moong)',
    category: 'Pulses',
    varieties: ['SML 668', 'PM 14-11', 'MH 421', 'IPM 02-14', 'CO 8'],
    season: 'Kharif/Rabi',
    durationDaysMin: 65,
    durationDaysMax: 85,
    soilTypes: ['Sandy Loam', 'Loamy', 'Alluvial', 'Black Cotton', 'Red Loamy'],
    waterRequirement: 'Low',
    temperatureMin: 22,
    temperatureMax: 35,
    states: ['Rajasthan', 'Madhya Pradesh', 'Maharashtra', 'Karnataka', 'Andhra Pradesh', 'Telangana', 'Tamil Nadu', 'Odisha', 'Chhattisgarh', 'Punjab'],
    seedRatePerAcre: '8–12 kg',
    seedCostPerAcre: { min: 1500, max: 2600 },
    cultivationCostPerAcre: { min: 8000, max: 14000 },
    expectedYieldPerAcre: { min: 6, max: 10, unit: 'quintals/acre' },
    pricePerQuintal: { min: 7500, max: 9500 },
    plantingWindows: ['Kharif: Jun–Jul', 'Zaid: Mar–Apr'],
    harvestMonths: 'Aug–Sep (Kharif), May–Jun (Zaid)',
    risks: ['Aphid/whitefly transmission of mosaic', 'Untimely rain at harvest'],
    commonPests: ['Whitefly', 'Aphids', 'Pod borer'],
    commonDiseases: ['Yellow mosaic', 'Powdery mildew'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Short-duration pulse ideal for quick rotations and after-crop in rice-wheat belts.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 80] }),
    cropRotationNotes: 'Great sequential crop after cereals.',
    organicFriendly: true,
    fallowSuitable: true,
  },
  {
    id: 'blackgram',
    name: 'Black Gram (Urad)',
    category: 'Pulses',
    varieties: ['T 9', 'PU 31', 'MDU 1', 'LBG 787', 'Pusa 6'],
    season: 'Kharif/Rabi',
    durationDaysMin: 70,
    durationDaysMax: 90,
    soilTypes: ['Clay Loam', 'Loamy', 'Alluvial', 'Black Cotton'],
    waterRequirement: 'Low',
    temperatureMin: 22,
    temperatureMax: 35,
    states: ['Andhra Pradesh', 'Telangana', 'Tamil Nadu', 'Madhya Pradesh', 'Maharashtra', 'Uttar Pradesh', 'Karnataka', 'Odisha'],
    seedRatePerAcre: '8–12 kg',
    seedCostPerAcre: { min: 1500, max: 2600 },
    cultivationCostPerAcre: { min: 8000, max: 14000 },
    expectedYieldPerAcre: { min: 6, max: 10, unit: 'quintals/acre' },
    pricePerQuintal: { min: 8000, max: 10000 },
    plantingWindows: ['Kharif: Jun–Jul', 'Rabi: Sep–Oct'],
    harvestMonths: 'Aug–Oct (Kharif), Nov–Dec (Rabi)',
    risks: ['YMV viral disease', 'Synchronous maturity issues', 'Sensitive to water logging'],
    commonPests: ['Whitefly', 'Pod borer'],
    commonDiseases: ['Yellow mosaic', 'Leaf crinkle'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Short-duration pulse with firm demand. Sensitive to water logging at germination.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 80] }),
    cropRotationNotes: 'Excellent as a rice-fallow crop in southern India.',
    organicFriendly: true,
  },
  {
    id: 'redgram',
    name: 'Red Gram',
    category: 'Pulses',
    varieties: ['Co 6', 'VBN 3', 'ICPL 87', 'Bori'],
    season: 'Kharif',
    durationDaysMin: 150,
    durationDaysMax: 220,
    soilTypes: ['Red Loamy', 'Black Cotton', 'Sandy Loam'],
    waterRequirement: 'Low',
    temperatureMin: 20,
    temperatureMax: 36,
    states: ['Tamil Nadu', 'Karnataka', 'Andhra Pradesh', 'Telangana', 'Maharashtra'],
    seedRatePerAcre: '6–8 kg',
    seedCostPerAcre: { min: 2000, max: 3200 },
    cultivationCostPerAcre: { min: 10000, max: 18000 },
    expectedYieldPerAcre: { min: 8, max: 12, unit: 'quintals/acre' },
    pricePerQuintal: { min: 8500, max: 11500 },
    plantingWindows: ['Kharif: May–Jun'],
    harvestMonths: 'Nov–Jan',
    risks: ['Long duration', 'Pod borer', 'Drought at flowering'],
    commonPests: ['Pod borer', 'Pod fly'],
    commonDiseases: ['Wilt', 'Sterility mosaic'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Red-seeded pigeonpea; similar agronomy to arhar with strong local demand.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 45], flower: [45, 75] }),
  },
  {
    id: 'lentil',
    name: 'Lentil (Masur)',
    category: 'Pulses',
    varieties: ['DPL 15', 'PL 406', 'PL 7', 'L 4076'],
    season: 'Rabi',
    durationDaysMin: 100,
    durationDaysMax: 130,
    soilTypes: ['Loamy', 'Clay Loam', 'Sandy Loam'],
    waterRequirement: 'Low',
    temperatureMin: 10,
    temperatureMax: 25,
    states: ['Uttar Pradesh', 'Madhya Pradesh', 'Bihar', 'West Bengal', 'Chhattisgarh', 'Rajasthan'],
    seedRatePerAcre: '30–40 kg',
    seedCostPerAcre: { min: 2000, max: 3200 },
    cultivationCostPerAcre: { min: 8000, max: 14000 },
    expectedYieldPerAcre: { min: 8, max: 12, unit: 'quintals/acre' },
    pricePerQuintal: { min: 7000, max: 9000 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Feb–Mar',
    risks: ['Poor draining soils cause wilt', 'Aphid attack in mild winters'],
    commonPests: ['Aphids', 'Pod borer'],
    commonDiseases: ['Fusarium wilt', 'Rust'],
    marketDemand: 'High',
    riskLevel: 'Low',
    description: 'Cool-season pulse well suited to rice-fallow and wheat rotation belts.',
    stageTemplates: stages(),
    organicFriendly: true,
    fallowSuitable: true,
  },
  {
    id: 'peas',
    name: 'Field Pea',
    category: 'Pulses',
    varieties: ['Bonus', 'Arkel (vegetable)', 'HUDP 15', 'IPFD 99-13'],
    season: 'Rabi',
    durationDaysMin: 90,
    durationDaysMax: 120,
    soilTypes: ['Loamy', 'Clay Loam', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 10,
    temperatureMax: 25,
    states: ['Uttar Pradesh', 'Bihar', 'Madhya Pradesh', 'Punjab', 'Haryana', 'West Bengal', 'Odisha'],
    seedRatePerAcre: '35–50 kg',
    seedCostPerAcre: { min: 2200, max: 3500 },
    cultivationCostPerAcre: { min: 9000, max: 15000 },
    expectedYieldPerAcre: { min: 10, max: 16, unit: 'quintals/acre' },
    pricePerQuintal: { min: 4000, max: 5500 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Jan–Mar',
    risks: ['Powdery mildew in humid winters', 'Pod borer'],
    commonPests: ['Pod borer', 'Leaf miner'],
    commonDiseases: ['Powdery mildew', 'Rust'],
    marketDemand: 'Medium',
    riskLevel: 'Low',
    description: 'Cool-season pulse/vegetable; improves soil nitrogen for next cereal.',
    stageTemplates: stages(),
    organicFriendly: true,
  },
  {
    id: 'cowpea',
    name: 'Cowpea',
    category: 'Pulses',
    varieties: ['CO 7', 'PGCP 5', 'Russian Giant', 'V 240'],
    season: 'Kharif/Zaid',
    durationDaysMin: 65,
    durationDaysMax: 90,
    soilTypes: ['Sandy Loam', 'Loamy', 'Alluvial', 'Red Loamy'],
    waterRequirement: 'Low',
    temperatureMin: 20,
    temperatureMax: 36,
    states: ['Rajasthan', 'Karnataka', 'Tamil Nadu', 'Maharashtra', 'Telangana', 'Gujarat', 'Odisha'],
    seedRatePerAcre: '8–12 kg',
    seedCostPerAcre: { min: 1200, max: 2200 },
    cultivationCostPerAcre: { min: 7000, max: 13000 },
    expectedYieldPerAcre: { min: 6, max: 10, unit: 'quintals/acre' },
    pricePerQuintal: { min: 6000, max: 7500 },
    plantingWindows: ['Kharif: Jun–Jul', 'Zaid: Feb–Mar'],
    harvestMonths: 'Aug–Oct',
    risks: ['Aphid vectors (mosaic)', 'Botrytis in wet spells'],
    commonPests: ['Aphids', 'Pod borer'],
    commonDiseases: ['Yellow mosaic', 'Botrytis'],
    marketDemand: 'Medium',
    riskLevel: 'Low',
    description: 'Fast pulse and green fodder; very drought tolerant in sandy soils.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 80] }),
    fallowSuitable: true,
    organicFriendly: true,
  },
  {
    id: 'groundnut',
    name: 'Groundnut',
    category: 'Oilseeds',
    varieties: ['JL 24', 'TG 37A', 'ICGV 91114', 'CO 7', 'Narayani'],
    season: 'Kharif/Rabi',
    durationDaysMin: 100,
    durationDaysMax: 130,
    soilTypes: ['Sandy', 'Sandy Loam', 'Loamy', 'Red Loamy'],
    waterRequirement: 'Medium',
    temperatureMin: 20,
    temperatureMax: 35,
    states: ['Gujarat', 'Andhra Pradesh', 'Telangana', 'Tamil Nadu', 'Karnataka', 'Maharashtra', 'Rajasthan'],
    seedRatePerAcre: '80–100 kg (shelled kennels)',
    seedCostPerAcre: { min: 4000, max: 6500 },
    cultivationCostPerAcre: { min: 12000, max: 20000 },
    expectedYieldPerAcre: { min: 12, max: 20, unit: 'quintals/acre (pods)' },
    pricePerQuintal: { min: 5500, max: 7500 },
    plantingWindows: ['Kharif: May–Jun', 'Rabi: Nov–Dec'],
    harvestMonths: 'Sep–Dec',
    risks: ['Moisture stress at peg formation', 'Tikka (leaf spot) disease', 'Seed cost high'],
    commonPests: ['Spodoptera', 'White grub'],
    commonDiseases: ['Tikka leaf spot', 'Rust', 'Stem rot'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Primary oilseed; performs best in light sandy loam. Exports support prices.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 50], flower: [50, 75] }),
    cropRotationNotes: 'Fix nitrogen; good in rotation with cereals.',
    organicFriendly: true,
  },
  {
    id: 'mustard',
    name: 'Mustard (Rapeseed-Mustard)',
    category: 'Oilseeds',
    varieties: ['Varuna', 'Pusa Bold (BIO 902)', 'NRCHB 101', 'Giriraj', 'Pusa Agrani'],
    season: 'Rabi',
    durationDaysMin: 95,
    durationDaysMax: 130,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial', 'Clay Loam'],
    waterRequirement: 'Medium',
    temperatureMin: 10,
    temperatureMax: 30,
    states: ['Rajasthan', 'Haryana', 'Uttar Pradesh', 'Madhya Pradesh', 'Gujarat', 'West Bengal', 'Assam', 'Rajasthan'],
    seedRatePerAcre: '3–5 kg',
    seedCostPerAcre: { min: 900, max: 1700 },
    cultivationCostPerAcre: { min: 9000, max: 15000 },
    expectedYieldPerAcre: { min: 12, max: 19, unit: 'quintals/acre' },
    pricePerQuintal: { min: 5400, max: 6500 },
    plantingWindows: ['Rabi: Sep–Oct (early), Oct–Nov (normal)'],
    harvestMonths: 'Feb–Mar',
    risks: ['Aphid infestation in humid winters', 'Blight in wet spells'],
    commonPests: ['Aphids', 'Sawfly', 'Cutworm'],
    commonDiseases: ['Alternaria blight', 'White rust', 'Downy mildew'],
    marketDemand: 'High',
    riskLevel: 'Low',
    description: 'Main rabi oilseed; India imports edible oils so domestic mustard demand is strong.',
    stageTemplates: stages(),
    organicFriendly: true,
  },
  {
    id: 'sesame',
    name: 'Sesame (Til)',
    category: 'Oilseeds',
    varieties: ['GT 10', 'GT 4', 'TMV 7', 'Savitri', 'Prachi'],
    season: 'Kharif/Zaid',
    durationDaysMin: 85,
    durationDaysMax: 110,
    soilTypes: ['Sandy Loam', 'Loamy', 'Black Cotton', 'Red Loamy'],
    waterRequirement: 'Low',
    temperatureMin: 18,
    temperatureMax: 38,
    states: ['Gujarat', 'Rajasthan', 'Madhya Pradesh', 'Maharashtra', 'Uttar Pradesh', 'Tamil Nadu', 'West Bengal'],
    seedRatePerAcre: '2–3.5 kg',
    seedCostPerAcre: { min: 900, max: 1800 },
    cultivationCostPerAcre: { min: 7000, max: 12000 },
    expectedYieldPerAcre: { min: 4, max: 7, unit: 'quintals/acre' },
    pricePerQuintal: { min: 11000, max: 15000 },
    plantingWindows: ['Kharif: Jun–Jul', 'Zaid: Feb–Mar'],
    harvestMonths: 'Aug–Oct (Kharif), May–Jun (Zaid)',
    risks: ['Low yields if rains uneven', 'Capsule shattering at harvest', 'Phyllody disease'],
    commonPests: ['Tobacco caterpillar', 'Jassids'],
    commonDiseases: ['Phyllody', 'Root rot'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'High-value oilseed with strong confectionery export demand; drought hardy.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 80] }),
    fallowSuitable: true,
    organicFriendly: true,
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    category: 'Oilseeds',
    varieties: ['KBSH 53', 'DBSF 12-3', 'Morden', 'GK 50'],
    season: 'Rabi/Zaid',
    durationDaysMin: 85,
    durationDaysMax: 110,
    soilTypes: ['Loamy', 'Sandy Loam', 'Black Cotton', 'Red Loamy'],
    waterRequirement: 'Low',
    temperatureMin: 20,
    temperatureMax: 35,
    states: ['Karnataka', 'Maharashtra', 'Telangana', 'Andhra Pradesh', 'Tamil Nadu', 'Odisha'],
    seedRatePerAcre: '3–5 kg',
    seedCostPerAcre: { min: 2200, max: 3800 },
    cultivationCostPerAcre: { min: 9000, max: 15000 },
    expectedYieldPerAcre: { min: 6, max: 11, unit: 'quintals/acre' },
    pricePerQuintal: { min: 6200, max: 7500 },
    plantingWindows: ['Rabi: Nov–Dec', 'Zaid: Feb'],
    harvestMonths: 'Feb–Apr (Rabi), May (Zaid)',
    risks: ['Bird damage', 'Necrosis virus in some regions', 'Price competition with imported oil'],
    commonPests: ['Head borer', 'Aphids'],
    commonDiseases: ['Downy mildew', 'Rust', 'Alternaria blight'],
    marketDemand: 'Medium',
    riskLevel: 'Medium',
    description: 'Short-duration oilseed; gives quick cash in rice-fallow systems.',
    stageTemplates: stages(),
    organicFriendly: true,
  },
  {
    id: 'soybean',
    name: 'Soybean',
    category: 'Oilseeds',
    varieties: ['JS 9560', 'JS 335', 'MACs 1407', 'NRC 138'],
    season: 'Kharif',
    durationDaysMin: 90,
    durationDaysMax: 115,
    soilTypes: ['Black Cotton', 'Clay Loam', 'Loamy', 'Red Loamy'],
    waterRequirement: 'Medium',
    temperatureMin: 20,
    temperatureMax: 34,
    states: ['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Chhattisgarh', 'Telangana', 'Karnataka', 'Gujarat'],
    seedRatePerAcre: '30–40 kg',
    seedCostPerAcre: { min: 2400, max: 4000 },
    cultivationCostPerAcre: { min: 10000, max: 17000 },
    expectedYieldPerAcre: { min: 12, max: 20, unit: 'quintals/acre' },
    pricePerQuintal: { min: 4200, max: 5200 },
    plantingWindows: ['Kharif: Jun–Jul'],
    harvestMonths: 'Sep–Oct',
    risks: ['Yellow mosaic virus (whitefly)', 'Girdle beetle', 'Water logging at germination'],
    commonPests: ['Girdle beetle', 'Whitefly', 'Semilooper'],
    commonDiseases: ['Yellow mosaic', 'Anthracnose', 'Rhizoctonia'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'High-protein oilseed and pulse substitute; backbone of rainfed central India.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 80] }),
    cropRotationNotes: 'Good with wheat in rotation.',
    organicFriendly: true,
  },
  {
    id: 'safflower',
    name: 'Safflower',
    category: 'Oilseeds',
    varieties: ['A-1', 'NARI 6', 'NARI 57', 'Bhima'],
    season: 'Rabi',
    durationDaysMin: 110,
    durationDaysMax: 150,
    soilTypes: ['Black Cotton', 'Clay Loam', 'Loamy'],
    waterRequirement: 'Low',
    temperatureMin: 8,
    temperatureMax: 32,
    states: ['Maharashtra', 'Karnataka', 'Telangana', 'Andhra Pradesh', 'Madhya Pradesh'],
    seedRatePerAcre: '8–10 kg',
    seedCostPerAcre: { min: 1800, max: 2800 },
    cultivationCostPerAcre: { min: 8000, max: 14000 },
    expectedYieldPerAcre: { min: 6, max: 10, unit: 'quintals/acre' },
    pricePerQuintal: { min: 6500, max: 8000 },
    plantingWindows: ['Rabi: Sep–Oct'],
    harvestMonths: 'Jan–Mar',
    risks: ['Small processing market', 'Low yields in excess moisture'],
    commonPests: ['Aphids', 'Safflower caterpillar'],
    commonDiseases: ['Wilt', 'Rust'],
    marketDemand: 'Low',
    riskLevel: 'Low',
    description: 'Drought-hardy oilseed for residual-moisture rabi in black soils.',
    stageTemplates: stages(),
    fallowSuitable: true,
    organicFriendly: true,
  },
  {
    id: 'cotton',
    name: 'Cotton',
    category: 'Commercial/Cash Crops',
    varieties: ['RCH 650', 'BG II', 'Arka 2', 'MCU 5', 'DCH 32'],
    season: 'Kharif',
    durationDaysMin: 140,
    durationDaysMax: 180,
    soilTypes: ['Black Cotton', 'Clay Loam', 'Loamy', 'Red Loamy', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 20,
    temperatureMax: 40,
    states: ['Maharashtra', 'Gujarat', 'Telangana', 'Andhra Pradesh', 'Punjab', 'Haryana', 'Karnataka', 'Rajasthan', 'Tamil Nadu', 'Madhya Pradesh'],
    seedRatePerAcre: '3–5 kg (desi), 2–3 kg (hybrid)',
    seedCostPerAcre: { min: 3200, max: 6000 },
    cultivationCostPerAcre: { min: 25000, max: 42000 },
    expectedYieldPerAcre: { min: 8, max: 14, unit: 'quintals/acre (kapas)' },
    pricePerQuintal: { min: 6500, max: 8500 },
    plantingWindows: ['Kharif: Apr–Jun'],
    harvestMonths: 'Oct–Dec',
    risks: ['Pink bollworm resistance', 'High cost with Bt seeds', 'Price swings with global fibres', 'Labour intensive picking'],
    commonPests: ['Pink bollworm', 'American bollworm', 'Whitefly', 'Thrips'],
    commonDiseases: ['Bacterial blight', 'Fusarium wilt', 'Leaf curl virus'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'High-value cash crop requiring high investment and pest vigilance. Best on black cotton soils with irrigation.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 55], flower: [55, 85] }),
    cropRotationNotes: 'Avoid continuous cotton; rotate with pulses/groundnut to suppress bollworm.',
  },
  {
    id: 'sugarcane',
    name: 'Sugarcane',
    category: 'Commercial/Cash Crops',
    varieties: ['Co 0238', 'Co 86032', 'Co 15023', 'Co 05002'],
    season: 'Kharif/Perennial',
    durationDaysMin: 300,
    durationDaysMax: 360,
    soilTypes: ['Loamy', 'Clay Loam', 'Alluvial', 'Black Cotton'],
    waterRequirement: 'High',
    temperatureMin: 20,
    temperatureMax: 38,
    states: ['Uttar Pradesh', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Punjab', 'Haryana', 'Bihar', 'Andhra Pradesh', 'Telangana'],
    seedRatePerAcre: '80–100 quintals (sets)',
    seedCostPerAcre: { min: 7200, max: 11000 },
    cultivationCostPerAcre: { min: 32000, max: 52000 },
    expectedYieldPerAcre: { min: 400, max: 600, unit: 'quintals/acre' },
    pricePerQuintal: { min: 320, max: 390 },
    plantingWindows: ['Plant: Feb–Mar (autumn), Sep–Oct (spring)'],
    harvestMonths: '11–12 months after planting',
    risks: ['Long duration ties up land', 'Heavy water and labour needs', 'Mills delay payments', 'Red rot disease'],
    commonPests: ['Shoot borer', 'Top borer', 'Mealybug'],
    commonDiseases: ['Red rot', 'Smut', 'Rust'],
    marketDemand: 'Medium',
    riskLevel: 'High',
    description: 'Long-duration crop with assured mill procurement but high water cost. Good in ratoon-supporting regions.',
    stageTemplates: stages({ germ: [10, 25], veg: [25, 70], flower: [70, 95] }),
    cropRotationNotes: 'Ratoon once, then rotate with wheat/pulses.',
  },
  {
    id: 'tobacco',
    name: 'Tobacco',
    category: 'Commercial/Cash Crops',
    varieties: ['FCV', 'Virginia Gold', 'Lanka', 'Bidi'],
    season: 'Rabi',
    durationDaysMin: 120,
    durationDaysMax: 150,
    soilTypes: ['Sandy Loam', 'Loamy', 'Red Loamy', 'Black Cotton'],
    waterRequirement: 'Medium',
    temperatureMin: 18,
    temperatureMax: 34,
    states: ['Andhra Pradesh', 'Telangana', 'Gujarat', 'Karnataka', 'Odisha'],
    seedRatePerAcre: '0.2–0.5 kg (transplant)',
    seedCostPerAcre: { min: 800, max: 1800 },
    cultivationCostPerAcre: { min: 22000, max: 38000 },
    expectedYieldPerAcre: { min: 10, max: 16, unit: 'quintals/acre (cured)' },
    pricePerQuintal: { min: 14000, max: 22000 },
    plantingWindows: ['Rabi: Sep–Nov'],
    harvestMonths: 'Jan–Mar',
    risks: ['High labour and curing costs', 'Regulatory/market restrictions', 'Strict quality grading'],
    commonPests: ['Tobacco caterpillar', 'Aphids'],
    commonDiseases: ['Mosaic virus', 'Black shank'],
    marketDemand: 'Low',
    riskLevel: 'High',
    description: 'High-value, high-effort cash crop sold through regulated auction platforms.',
    stageTemplates: stages(),
  },
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'Vegetables',
    varieties: ['Rashmi', 'Hima', 'Jyothi', 'Suraksha', 'Vaibhav', 'Arka Rakshak', 'Arka Abhed'],
    season: 'Kharif/Rabi/Zaid',
    durationDaysMin: 80,
    durationDaysMax: 110,
    soilTypes: ['Loamy', 'Sandy Loam', 'Clay Loam', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: 15,
    temperatureMax: 35,
    states: ['Andhra Pradesh', 'Telangana', 'Karnataka', 'Maharashtra', 'Tamil Nadu', 'Odisha', 'Madhya Pradesh', 'Gujarat', 'Haryana', 'Uttar Pradesh'],
    seedRatePerAcre: '150–250 g (seedlings)',
    seedCostPerAcre: { min: 1800, max: 3800 },
    cultivationCostPerAcre: { min: 16000, max: 28000 },
    expectedYieldPerAcre: { min: 100, max: 180, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1100, max: 2500 },
    plantingWindows: ['Kharif: Jun–Jul', 'Rabi: Oct–Nov', 'Zaid: Feb'],
    harvestMonths: 'Aug–Nov (Kharif), Feb–Apr (Rabi)',
    risks: ['Severe price swings at glut', 'Late blight in humid spells', 'Leaf curl virus (whitefly)', 'Short shelf life'],
    commonPests: ['Fruit borer', 'Whitefly', 'Aphids', 'Mites'],
    commonDiseases: ['Late blight', 'Early blight', 'Leaf curl virus', 'Bacterial wilt'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Short-cycle vegetable with very buffered demand but notorious price volatility and disease pressure.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 50], flower: [50, 80] }),
    cropRotationNotes: 'Avoid Solanaceae-after-Solanaceae; rotate with legumes/cereals.',
  },
  {
    id: 'onion',
    name: 'Onion',
    category: 'Vegetables',
    varieties: ['N-53', 'Phule Samarth', 'Agrifound Light Red', 'Nasik Red', 'Bhima Super'],
    season: 'Kharif/Rabi',
    durationDaysMin: 90,
    durationDaysMax: 120,
    soilTypes: ['Sandy Loam', 'Loamy', 'Clay Loam', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: 13,
    temperatureMax: 35,
    states: ['Maharashtra', 'Karnataka', 'Madhya Pradesh', 'Gujarat', 'Rajasthan', 'Bihar', 'Tamil Nadu', 'Andhra Pradesh', 'Telangana'],
    seedRatePerAcre: '3–4 kg (direct), 4–5 kg (nursery)',
    seedCostPerAcre: { min: 1800, max: 4000 },
    cultivationCostPerAcre: { min: 18000, max: 32000 },
    expectedYieldPerAcre: { min: 120, max: 220, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1600, max: 2800 },
    plantingWindows: ['Kharif: May–Jun', 'Rabi: Oct–Nov'],
    harvestMonths: '98–120 days after planting',
    risks: ['Price collapse in surplus years', 'Thrips and purple blotch', 'Needs careful curing after harvest'],
    commonPests: ['Thrips', 'Onion maggot'],
    commonDiseases: ['Purple blotch', 'Downy mildew', 'Smut'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'High-volatility but indispensable kitchen crop; excellent when grown in off-season windows.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 60], flower: [60, 85] }),
  },
  {
    id: 'potato',
    name: 'Potato',
    category: 'Vegetables',
    varieties: ['Kufri Jyoti', 'Kufri Pukhraj', 'Kufri Chandramukhi', 'Kufri Badshah', 'Kufri Chipsona 3'],
    season: 'Rabi',
    durationDaysMin: 80,
    durationDaysMax: 110,
    soilTypes: ['Sandy Loam', 'Loamy', 'Alluvial', 'Loam'],
    waterRequirement: 'High',
    temperatureMin: 8,
    temperatureMax: 25,
    states: ['Uttar Pradesh', 'West Bengal', 'Bihar', 'Punjab', 'Gujarat', 'Madhya Pradesh', 'Assam', 'Karnataka', 'Tamil Nadu'],
    seedRatePerAcre: '10–12 quintals (tubers)',
    seedCostPerAcre: { min: 9000, max: 15000 },
    cultivationCostPerAcre: { min: 22000, max: 35000 },
    expectedYieldPerAcre: { min: 180, max: 300, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1100, max: 1800 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Jan–Mar',
    risks: ['Seed tuber cost high', 'Late blight in wet winters', 'Cold storage needed for holding stock'],
    commonPests: ['Cutworm', 'Aphids (virus spread)'],
    commonDiseases: ['Late blight', 'Early blight', 'Black scurf'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Remunerative rabi vegetable for alluvial belts with cold winters; stored to extend sale window.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 55], flower: [55, 80] }),
  },
  {
    id: 'chilli',
    name: 'Chilli',
    category: 'Vegetables',
    varieties: ['Teja', 'Byadgi', 'Guntur 4', 'Kashi Anmol', 'PKM 1'],
    season: 'Kharif/Rabi',
    durationDaysMin: 110,
    durationDaysMax: 150,
    soilTypes: ['Loamy', 'Sandy Loam', 'Black Cotton', 'Red Loamy'],
    waterRequirement: 'Medium',
    temperatureMin: 18,
    temperatureMax: 35,
    states: ['Andhra Pradesh', 'Telangana', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Madhya Pradesh', 'Gujarat', 'Odisha'],
    seedRatePerAcre: '400–600 g',
    seedCostPerAcre: { min: 2500, max: 5000 },
    cultivationCostPerAcre: { min: 16000, max: 28000 },
    expectedYieldPerAcre: { min: 40, max: 80, unit: 'quintals/acre (dry)' },
    pricePerQuintal: { min: 7500, max: 12000 },
    plantingWindows: ['Kharif: Jun–Jul', 'Rabi: Oct–Nov'],
    harvestMonths: 'Sep–Dec (Kharif), Jan–Apr (Rabi)',
    risks: ['Mosaic virus via thrips/whitefly', 'Powdery mildew in dry heat', 'Colour/moisture grading affects price'],
    commonPests: ['Thrips', 'Whitefly', 'Fruit borer'],
    commonDiseases: ['Leaf curl', 'Powdery mildew', 'Damping off'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Profitable spice/vegetable with strong domestic and export demand, especially in rainfed red-soil belts.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 55], flower: [55, 80] }),
    organicFriendly: true,
  },
  {
    id: 'brinjal',
    name: 'Brinjal (Eggplant)',
    category: 'Vegetables',
    varieties: ['Arka Keshav', 'Pusa Shyamla', 'Arka Anand', 'JB 64', 'Utkal Madhuri'],
    season: 'Kharif/Rabi',
    durationDaysMin: 100,
    durationDaysMax: 130,
    soilTypes: ['Loamy', 'Sandy Loam', 'Clay Loam', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 18,
    temperatureMax: 35,
    states: ['West Bengal', 'Bihar', 'Odisha', 'Andhra Pradesh', 'Telangana', 'Karnataka', 'Uttar Pradesh', 'Gujarat'],
    seedRatePerAcre: '250–400 g',
    seedCostPerAcre: { min: 2000, max: 4000 },
    cultivationCostPerAcre: { min: 14000, max: 24000 },
    expectedYieldPerAcre: { min: 120, max: 200, unit: 'quintals/acre' },
    pricePerQuintal: { min: 900, max: 1800 },
    plantingWindows: ['Kharif: Jun–Jul', 'Rabi: Oct–Nov'],
    harvestMonths: 'Sep–Feb',
    risks: ['Fruit and shoot borer', 'Whitefly/viral complex', 'Price dips at harvest peaks'],
    commonPests: ['Fruit & shoot borer', 'Whitefly', 'Aphids'],
    commonDiseases: ['Bacterial wilt', 'Phomopsis blight', 'Mosaic'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'High-yielding storable vegetable; needs regular picking to keep quality.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 55], flower: [55, 80] }),
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    category: 'Leafy Vegetables',
    varieties: ['Golden Acre', 'Pusa Drumhead', 'Pusa Mukta', 'Pride of India'],
    season: 'Rabi',
    durationDaysMin: 70,
    durationDaysMax: 90,
    soilTypes: ['Loamy', 'Clay Loam', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: 10,
    temperatureMax: 25,
    states: ['West Bengal', 'Odisha', 'Bihar', 'Uttar Pradesh', 'Punjab', 'Haryana', 'Assam', 'Karnataka'],
    seedRatePerAcre: '350–450 g',
    seedCostPerAcre: { min: 1800, max: 3500 },
    cultivationCostPerAcre: { min: 14000, max: 24000 },
    expectedYieldPerAcre: { min: 140, max: 220, unit: 'quintals/acre' },
    pricePerQuintal: { min: 700, max: 1400 },
    plantingWindows: ['Rabi: Sep–Oct'],
    harvestMonths: 'Dec–Feb',
    risks: ['Diamondback moth', 'Slugs in wet spells', 'Heads crack if rain follows dry spell'],
    commonPests: ['Diamondback moth', 'Aphids', 'Cabbage butterfly'],
    commonDiseases: ['Black rot', 'Club root', 'Downy mildew'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Quick, cool-season leafy vegetable with steady urban demand.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 60], flower: [60, 85] }),
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    category: 'Vegetables',
    varieties: ['Pusa Snowball K-1', 'Pusa Deepali', 'Kaveri', 'Snow King'],
    season: 'Rabi',
    durationDaysMin: 80,
    durationDaysMax: 110,
    soilTypes: ['Loamy', 'Clay Loam', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: 10,
    temperatureMax: 24,
    states: ['West Bengal', 'Bihar', 'Odisha', 'Uttar Pradesh', 'Punjab', 'Haryana', 'Assam', 'Karnataka'],
    seedRatePerAcre: '350–450 g',
    seedCostPerAcre: { min: 2000, max: 4000 },
    cultivationCostPerAcre: { min: 15000, max: 26000 },
    expectedYieldPerAcre: { min: 120, max: 200, unit: 'quintals/acre' },
    pricePerQuintal: { min: 800, max: 1700 },
    plantingWindows: ['Rabi: Sep–Oct'],
    harvestMonths: 'Dec–Mar',
    risks: ['Curd quality drops in heat', 'Diamondback moth', 'Blind curds if transplant mismanaged'],
    commonPests: ['Diamondback moth', 'Aphids'],
    commonDiseases: ['Black rot', 'Downy mildew'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Premium vegetable for cool season; strict moisture and curd-cover management.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 55], flower: [55, 85] }),
  },
  {
    id: 'carrot',
    name: 'Carrot',
    category: 'Vegetables',
    varieties: ['Pusa Kesari', 'Pusa Meghali', 'Nantes', 'Early Nantes'],
    season: 'Rabi',
    durationDaysMin: 80,
    durationDaysMax: 100,
    soilTypes: ['Sandy Loam', 'Loamy', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 10,
    temperatureMax: 28,
    states: ['Punjab', 'Haryana', 'Uttar Pradesh', 'West Bengal', 'Karnataka', 'Tamil Nadu', 'Assam'],
    seedRatePerAcre: '2–3 kg',
    seedCostPerAcre: { min: 1600, max: 2800 },
    cultivationCostPerAcre: { min: 12000, max: 20000 },
    expectedYieldPerAcre: { min: 120, max: 200, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1100, max: 2000 },
    plantingWindows: ['Rabi: Sep–Nov'],
    harvestMonths: 'Jan–Mar',
    risks: ['Root forking in stony soils', 'Aphid/leaf blight in humid spells'],
    commonPests: ['Aphids', 'Root knot nematode'],
    commonDiseases: ['Leaf blight', 'Powdery mildew'],
    marketDemand: 'High',
    riskLevel: 'Low',
    description: 'Easy-market root vegetable suited to sandy loam with loose, deep tilth.',
    stageTemplates: stages(),
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    category: 'Vegetables',
    varieties: ['Pusa Uday', 'Poinsettte', 'Krishna', 'AAUC 2'],
    season: 'Kharif/Zaid',
    durationDaysMin: 65,
    durationDaysMax: 90,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 18,
    temperatureMax: 35,
    states: ['Andhra Pradesh', 'Telangana', 'Karnataka', 'Odisha', 'Tamil Nadu', 'Uttar Pradesh', 'Punjab'],
    seedRatePerAcre: '1–1.5 kg',
    seedCostPerAcre: { min: 1800, max: 3200 },
    cultivationCostPerAcre: { min: 10000, max: 18000 },
    expectedYieldPerAcre: { min: 80, max: 140, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1100, max: 2200 },
    plantingWindows: ['Kharif: Jun–Jul', 'Zaid: Feb–Mar'],
    harvestMonths: 'Aug–Oct, May–Jul',
    risks: ['Powdery mildew', 'Aphids', 'Price drop at glut'],
    commonPests: ['Aphids', 'Fruit fly'],
    commonDiseases: ['Powdery mildew', 'Downy mildew'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Fast, high-frequency-picking vine vegetable for warm seasons.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 60], flower: [60, 85] }),
  },
  {
    id: 'okra',
    name: 'Okra (Bhindi)',
    category: 'Vegetables',
    varieties: ['Arka Anamika', 'Varsha Upahar', 'Pusa Sawani', 'Hybrid OH-16'],
    season: 'Kharif/Zaid',
    durationDaysMin: 70,
    durationDaysMax: 100,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial', 'Red Loamy'],
    waterRequirement: 'Medium',
    temperatureMin: 20,
    temperatureMax: 38,
    states: ['Andhra Pradesh', 'Telangana', 'Karnataka', 'Gujarat', 'Maharashtra', 'Uttar Pradesh', 'Bihar', 'Odisha'],
    seedRatePerAcre: '3–4 kg',
    seedCostPerAcre: { min: 2000, max: 4000 },
    cultivationCostPerAcre: { min: 11000, max: 19000 },
    expectedYieldPerAcre: { min: 70, max: 120, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1700, max: 3200 },
    plantingWindows: ['Kharif: Jun–Jul', 'Zaid: Feb–Mar'],
    harvestMonths: 'Aug–Oct (Kharif), May–Jun (Zaid)',
    risks: ['Yellow vein mosaic virus', 'Fruit borer', 'Frequent picking needed'],
    commonPests: ['Fruit and shoot borer', 'Whitefly', 'Leaf hopper'],
    commonDiseases: ['Yellow vein mosaic', 'Powdery mildew'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'High-frequency-harvest vegetable tolerant of heat; robust demand in south and central India.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 60], flower: [60, 85] }),
  },
  {
    id: 'bitter_gourd',
    name: 'Bitter Gourd (Karela)',
    category: 'Vegetables',
    varieties: ['Pusa Vishesh', 'Arka Harit', 'MDU 1', 'Phule Green Gold'],
    season: 'Kharif',
    durationDaysMin: 90,
    durationDaysMax: 120,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 20,
    temperatureMax: 36,
    states: ['Maharashtra', 'Gujarat', 'Karnataka', 'Tamil Nadu', 'Andhra Pradesh', 'Odisha', 'Uttar Pradesh'],
    seedRatePerAcre: '1.5–2.5 kg',
    seedCostPerAcre: { min: 2200, max: 4000 },
    cultivationCostPerAcre: { min: 11000, max: 20000 },
    expectedYieldPerAcre: { min: 60, max: 110, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1700, max: 3000 },
    plantingWindows: ['Kharif: Jun–Jul'],
    harvestMonths: 'Aug–Nov',
    risks: ['Fruit fly', 'Damping off in seedbed'],
    commonPests: ['Fruit fly', 'Mites', 'Aphids'],
    commonDiseases: ['Powdery mildew', 'Mosaic'],
    marketDemand: 'Medium',
    riskLevel: 'Low',
    description: 'Stable-demand specialty vegetable with good cold-chain tolerance.',
    stageTemplates: stages(),
  },
  {
    id: 'bottle_gourd',
    name: 'Bottle Gourd (Lauki)',
    category: 'Vegetables',
    varieties: ['Pusa Naveen', 'Pusa Santushti', 'Arka Bahar', 'Shreya'],
    season: 'Kharif/Rabi',
    durationDaysMin: 80,
    durationDaysMax: 110,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: 18,
    temperatureMax: 35,
    states: ['Uttar Pradesh', 'Bihar', 'West Bengal', 'Maharashtra', 'Karnataka', 'Odisha', 'Gujarat'],
    seedRatePerAcre: '1–1.5 kg',
    seedCostPerAcre: { min: 1600, max: 3000 },
    cultivationCostPerAcre: { min: 10000, max: 18000 },
    expectedYieldPerAcre: { min: 100, max: 170, unit: 'quintals/acre' },
    pricePerQuintal: { min: 800, max: 1500 },
    plantingWindows: ['Kharif: Jun–Jul', 'Rabi: Oct–Nov'],
    harvestMonths: 'Aug–Nov (Kharif), Jan–Mar (Rabi)',
    risks: ['Fruit fly', 'Whiteflies', 'Excess fruit load weakens vine'],
    commonPests: ['Fruit fly', 'Aphids'],
    commonDiseases: ['Powdery mildew', 'Leaf spot'],
    marketDemand: 'High',
    riskLevel: 'Low',
    description: 'Heavy-yielding vine vegetable with steady kitchen demand.',
    stageTemplates: stages(),
  },
  {
    id: 'ridge_gourd',
    name: 'Ridge Gourd (Turai)',
    category: 'Vegetables',
    varieties: ['Pusa Nasdar', 'Arka Prasan', 'Jaipur Long'],
    season: 'Kharif',
    durationDaysMin: 75,
    durationDaysMax: 100,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 20,
    temperatureMax: 36,
    states: ['Uttar Pradesh', 'Maharashtra', 'Karnataka', 'Odisha', 'Andhra Pradesh', 'Tamil Nadu'],
    seedRatePerAcre: '1–1.5 kg',
    seedCostPerAcre: { min: 1500, max: 2800 },
    cultivationCostPerAcre: { min: 9000, max: 17000 },
    expectedYieldPerAcre: { min: 90, max: 150, unit: 'quintals/acre' },
    pricePerQuintal: { min: 900, max: 1600 },
    plantingWindows: ['Kharif: Jun–Jul'],
    harvestMonths: 'Aug–Nov',
    risks: ['Fruit fly', 'Late season powdery mildew'],
    commonPests: ['Fruit fly', 'Aphids'],
    commonDiseases: ['Powdery mildew'],
    marketDemand: 'Medium',
    riskLevel: 'Low',
    description: 'Fast-growing vine vegetable with low input needs.',
    stageTemplates: stages(),
  },
  {
    id: 'cabbage_leaf',
    name: 'Leafy Greens (Palak/Sarso)',
    category: 'Leafy Vegetables',
    varieties: ['Pusa Bharati (Palak)', 'Allgreen', 'Bangalore Spinach', 'Toria'],
    season: 'Kharif/Rabi/Zaid',
    durationDaysMin: 40,
    durationDaysMax: 60,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 15,
    temperatureMax: 32,
    states: ['Uttar Pradesh', 'Punjab', 'Haryana', 'West Bengal', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Gujarat'],
    seedRatePerAcre: '8–12 kg',
    seedCostPerAcre: { min: 1600, max: 3000 },
    cultivationCostPerAcre: { min: 8000, max: 14000 },
    expectedYieldPerAcre: { min: 80, max: 140, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1100, max: 2200 },
    plantingWindows: ['Multiple pickings across year'],
    harvestMonths: 'Year-round with staggered sowing',
    risks: ['Bolting in heat', 'Aphids and leaf miner', 'Short shelf life'],
    commonPests: ['Aphids', 'Leaf miner'],
    commonDiseases: ['Downy mildew', 'Leaf spot'],
    marketDemand: 'High',
    riskLevel: 'Low',
    description: 'Quick-return leafy crop ideal for peri-urban vegetable gardens.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 80], flower: [80, 100] }),
    fallowSuitable: true,
    organicFriendly: true,
  },
  {
    id: 'coriander',
    name: 'Coriander (Dhania)',
    category: 'Spices',
    varieties: ['Sujata', 'Sindhu', 'RCR 435', 'Gujarat Coriander 2', 'CO 4'],
    season: 'Rabi',
    durationDaysMin: 80,
    durationDaysMax: 110,
    soilTypes: ['Loamy', 'Sandy Loam', 'Black Cotton', 'Alluvial'],
    waterRequirement: 'Low',
    temperatureMin: 12,
    temperatureMax: 32,
    states: ['Rajasthan', 'Madhya Pradesh', 'Gujarat', 'Karnataka', 'Telangana', 'Andhra Pradesh', 'Tamil Nadu', 'Uttar Pradesh'],
    seedRatePerAcre: '10–12 kg (seed)',
    seedCostPerAcre: { min: 2000, max: 4200 },
    cultivationCostPerAcre: { min: 9000, max: 16000 },
    expectedYieldPerAcre: { min: 6, max: 9, unit: 'quintals/acre (seed)' },
    pricePerQuintal: { min: 9000, max: 14000 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Jan–Mar',
    risks: ['Aphid pressure', 'Powdery mildew in humid spells', 'Grain shrivelling with heat at maturity'],
    commonPests: ['Aphids', 'Semi looper'],
    commonDiseases: ['Powdery mildew', 'Wilt'],
    marketDemand: 'High',
    riskLevel: 'Low',
    description: 'Low-water spice with firm domestic and export demand.',
    stageTemplates: stages(),
    organicFriendly: true,
  },
  {
    id: 'garlic',
    name: 'Garlic',
    category: 'Spices',
    varieties: ['Yamuna Safed', 'Yamuna Safed 3', 'G-282', 'Bhima Om'],
    season: 'Rabi',
    durationDaysMin: 100,
    durationDaysMax: 135,
    soilTypes: ['Sandy Loam', 'Loamy', 'Clay Loam', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 12,
    temperatureMax: 26,
    states: ['Madhya Pradesh', 'Gujarat', 'Rajasthan', 'Uttar Pradesh', 'Karnataka', 'Maharashtra', 'Punjab'],
    seedRatePerAcre: '400–500 kg (cloves)',
    seedCostPerAcre: { min: 9000, max: 18000 },
    cultivationCostPerAcre: { min: 18000, max: 32000 },
    expectedYieldPerAcre: { min: 40, max: 80, unit: 'quintals/acre' },
    pricePerQuintal: { min: 14000, max: 26000 },
    plantingWindows: ['Rabi: Aug–Oct'],
    harvestMonths: 'Jan–Mar',
    risks: ['Viral complexes reduce bulb size', 'High seed (clove) cost', 'Purple blotch in humid weather'],
    commonPests: ['Thrips', 'Aphids'],
    commonDiseases: ['Purple blotch', 'Downy mildew', 'White rot'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Premium-priced bulb crop with high seed cost; ideal for well-drained soils.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 55], flower: [55, 85] }),
  },
  {
    id: 'turmeric',
    name: 'Turmeric',
    category: 'Spices',
    varieties: ['Salem', 'Erode', 'PTS 24', 'Prathibha', 'Megha Turmeric 1', 'Suranjana'],
    season: 'Kharif',
    durationDaysMin: 210,
    durationDaysMax: 240,
    soilTypes: ['Loamy', 'Clay Loam', 'Alluvial', 'Black Cotton'],
    waterRequirement: 'High',
    temperatureMin: 18,
    temperatureMax: 35,
    states: ['Telangana', 'Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Odisha', 'West Bengal'],
    seedRatePerAcre: '8–10 quintals (rhizomes)',
    seedCostPerAcre: { min: 12000, max: 20000 },
    cultivationCostPerAcre: { min: 28000, max: 48000 },
    expectedYieldPerAcre: { min: 50, max: 90, unit: 'quintals/acre (raw)' },
    pricePerQuintal: { min: 8000, max: 14000 },
    plantingWindows: ['Kharif: Apr–Jun'],
    harvestMonths: 'Nov–Feb',
    risks: ['Long duration', 'Rhizome rot in water logging', 'High seed material cost'],
    commonPests: ['Rhizome scale', 'Shoot borer'],
    commonDiseases: ['Rhizome rot', 'Leaf blotch'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Long-cycle high-value spice; processing (boiling/sun-drying) improves returns.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 60], flower: [60, 85] }),
  },
  {
    id: 'ginger',
    name: 'Ginger',
    category: 'Spices',
    varieties: ['Rio-de-Janeiro', 'Maran', 'Nadia', 'Suprabha', 'Varada'],
    season: 'Kharif',
    durationDaysMin: 180,
    durationDaysMax: 210,
    soilTypes: ['Loamy', 'Clay Loam', 'Laterite', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: 15,
    temperatureMax: 30,
    states: ['Kerala', 'Karnataka', 'Odisha', 'North East', 'Maharashtra', 'West Bengal', 'Telangana'],
    seedRatePerAcre: '10–14 quintals (rhizomes)',
    seedCostPerAcre: { min: 16000, max: 26000 },
    cultivationCostPerAcre: { min: 32000, max: 55000 },
    expectedYieldPerAcre: { min: 60, max: 100, unit: 'quintals/acre' },
    pricePerQuintal: { min: 9000, max: 16000 },
    plantingWindows: ['Kharif: Apr–Jun'],
    harvestMonths: 'Nov–Jan',
    risks: ['Seed rhizome cost very high', 'Bacterial wilt and soft rot', 'Long duration'],
    commonPests: ['Rhizome scale', 'Borer'],
    commonDiseases: ['Bacterial wilt', 'Soft rot', 'Leaf spot'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'High-value spice suited to humid, well-drained soils; requires heavy inputs and care.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 60], flower: [60, 85] }),
  },
  {
    id: 'fennel',
    name: 'Fennel (Saunf)',
    category: 'Spices',
    varieties: ['RF 125', 'Gujarat Fennel 1', 'PF 35'],
    season: 'Rabi',
    durationDaysMin: 110,
    durationDaysMax: 140,
    soilTypes: ['Loamy', 'Sandy Loam', 'Clay Loam', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 8,
    temperatureMax: 32,
    states: ['Gujarat', 'Rajasthan', 'Uttar Pradesh', 'Madhya Pradesh', 'Haryana', 'Punjab'],
    seedRatePerAcre: '4–6 kg',
    seedCostPerAcre: { min: 1200, max: 2400 },
    cultivationCostPerAcre: { min: 9000, max: 15000 },
    expectedYieldPerAcre: { min: 10, max: 16, unit: 'quintals/acre' },
    pricePerQuintal: { min: 12000, max: 17000 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Feb–Apr',
    risks: ['Frost at flowering', 'Aphids in mild winters'],
    commonPests: ['Aphids', 'Cutworm'],
    commonDiseases: ['Powdery mildew', 'Blights'],
    marketDemand: 'High',
    riskLevel: 'Low',
    description: 'Export-oriented spice with strong rabi fit in Gujarat-Rajasthan belt.',
    stageTemplates: stages(),
    organicFriendly: true,
  },
  {
    id: 'cumin',
    name: 'Cumin (Jeera)',
    category: 'Spices',
    varieties: ['GC 4', 'MC 43', 'RZ 209', 'Gujarat Cumin 1'],
    season: 'Rabi',
    durationDaysMin: 95,
    durationDaysMax: 125,
    soilTypes: ['Sandy Loam', 'Loamy', 'Sandy', 'Alluvial'],
    waterRequirement: 'Low',
    temperatureMin: 10,
    temperatureMax: 34,
    states: ['Gujarat', 'Rajasthan', 'Haryana', 'Madhya Pradesh', 'Uttar Pradesh'],
    seedRatePerAcre: '5–6 kg',
    seedCostPerAcre: { min: 2200, max: 4800 },
    cultivationCostPerAcre: { min: 9000, max: 16000 },
    expectedYieldPerAcre: { min: 4, max: 7, unit: 'quintals/acre' },
    pricePerQuintal: { min: 17000, max: 24000 },
    plantingWindows: ['Rabi: Oct–Nov'],
    harvestMonths: 'Feb–Apr',
    risks: ['Powdery mildew in wet spells', 'Frost at flowering', 'Price very volatile'],
    commonPests: ['Aphids', 'Sucking pests'],
    commonDiseases: ['Powdery mildew', 'Wilt'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Premium spice for arid/semi-arid rabi; prices swing sharply with production.',
    stageTemplates: stages(),
    fallowSuitable: true,
    organicFriendly: true,
  },
  {
    id: 'black_pepper',
    name: 'Black Pepper',
    category: 'Spices',
    varieties: ['Panniyur-1', 'Panniyur-5', 'Karimunda', 'Kalluvally', 'Jeerakamunda'],
    season: 'Perennial',
    durationDaysMin: 1095,
    durationDaysMax: 3650,
    soilTypes: ['Laterite', 'Loamy', 'Red Loamy'],
    waterRequirement: 'Medium',
    temperatureMin: 20,
    temperatureMax: 35,
    states: ['Kerala', 'Karnataka', 'Tamil Nadu', 'Goa', 'Maharashtra'],
    seedRatePerAcre: '700–1000 vines',
    seedCostPerAcre: { min: 20000, max: 35000 },
    cultivationCostPerAcre: { min: 25000, max: 45000 },
    expectedYieldPerAcre: { min: 6, max: 12, unit: 'quintals/acre (dry)' },
    pricePerQuintal: { min: 60000, max: 80000 },
    plantingWindows: ['Planting: May–Jun (before monsoon)'],
    harvestMonths: 'Nov–Mar (main), Apr–Jun (bulk)',
    risks: ['Slow establishment', 'Wilt (foot rot)', 'Very long payback', 'Needs support trees'],
    commonPests: ['Pollu beetle', 'Shot hole borer'],
    commonDiseases: ['Foot rot', 'Slow decline'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Long-term plantation spice for humid coastal hills; not a short-cycle option.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 50], flower: [50, 80] }),
  },
  {
    id: 'mango',
    name: 'Mango',
    category: 'Fruits',
    varieties: ['Alphonso', 'Totapuri', 'Kesar', 'Langra', 'Dashehari', 'Neelum', 'Chausa', 'Banganapalli'],
    season: 'Perennial',
    durationDaysMin: 2190,
    durationDaysMax: 3650,
    soilTypes: ['Laterite', 'Loamy', 'Sandy Loam', 'Red Loamy', 'Black Cotton'],
    waterRequirement: 'Medium',
    temperatureMin: 15,
    temperatureMax: 40,
    states: ['Maharashtra', 'Andhra Pradesh', 'Telangana', 'Uttar Pradesh', 'Karnataka', 'Gujarat', 'Bihar', 'West Bengal', 'Tamil Nadu'],
    seedRatePerAcre: '60–80 plants',
    seedCostPerAcre: { min: 15000, max: 30000 },
    cultivationCostPerAcre: { min: 30000, max: 60000 },
    expectedYieldPerAcre: { min: 50, max: 150, unit: 'quintals/acre (mature orchard)' },
    pricePerQuintal: { min: 1200, max: 4000 },
    plantingWindows: ['Planting: Jun–Aug (monsoon)'],
    harvestMonths: 'Apr–Jul (depending on variety)',
    risks: ['Long pre-bearing period', 'Alternate bearing', 'Mango hopper and mealy bug', 'Flower drop in unseasonal rain'],
    commonPests: ['Mango hopper', 'Mealy bug', 'Stem borer'],
    commonDiseases: ['Powdery mildew', 'Anthracnose', 'Black tip'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Long-term orchard investment. High-value fruit with export potential; needs patient multi-year planning.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 90] }),
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruits',
    varieties: ['Grand Naine', 'Robusta', 'Nendran', 'Poovan', 'Rasthali', 'Dwarf Cavendish'],
    season: 'Perennial',
    durationDaysMin: 320,
    durationDaysMax: 380,
    soilTypes: ['Loamy', 'Clay Loam', 'Sandy Loam', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: 20,
    temperatureMax: 38,
    states: ['Tamil Nadu', 'Maharashtra', 'Gujarat', 'Karnataka', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'West Bengal'],
    seedRatePerAcre: '700–1000 suckers (tissue culture)',
    seedCostPerAcre: { min: 25000, max: 45000 },
    cultivationCostPerAcre: { min: 60000, max: 110000 },
    expectedYieldPerAcre: { min: 200, max: 330, unit: 'quintals/acre' },
    pricePerQuintal: { min: 2500, max: 4500 },
    plantingWindows: ['Planting: May–Jun and Aug–Sep'],
    harvestMonths: '11–12 months after planting',
    risks: ['High initial cost (TC plants)', 'Sigatoka and Panama wilt', 'Wind damage', 'Very water hungry'],
    commonPests: ['Banana weevil', 'Thrips', 'Nematodes'],
    commonDiseases: ['Sigatoka', 'Panama wilt', 'Bunchy top virus'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'High-return, high-cost fruit crop under irrigation. Tissue culture plants preferred.',
    stageTemplates: stages({ germ: [10, 25], veg: [25, 60], flower: [60, 90] }),
  },
  {
    id: 'papaya',
    name: 'Papaya',
    category: 'Fruits',
    varieties: ['Pusa Nanha', 'Red Lady', 'Washington', 'CO 2', 'Surya'],
    season: 'Perennial',
    durationDaysMin: 270,
    durationDaysMax: 330,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial', 'Red Loamy'],
    waterRequirement: 'High',
    temperatureMin: 18,
    temperatureMax: 38,
    states: ['Andhra Pradesh', 'Telangana', 'Karnataka', 'Maharashtra', 'Gujarat', 'Tamil Nadu', 'Odisha', 'Madhya Pradesh'],
    seedRatePerAcre: '500–700 plants',
    seedCostPerAcre: { min: 6000, max: 12000 },
    cultivationCostPerAcre: { min: 25000, max: 42000 },
    expectedYieldPerAcre: { min: 200, max: 350, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1800, max: 3000 },
    plantingWindows: ['Planting: Feb–Mar and Jun–Jul'],
    harvestMonths: '9–11 months after planting',
    risks: ['Ring spot virus', 'Root rot in water logging', 'Wind topples tall plants'],
    commonPests: ['Papaya mealybug', 'Aphids', 'Fruit fly'],
    commonDiseases: ['Ring spot', 'Root rot', 'Anthracnose'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Fast-bearing tropical fruit well suited to small farms with assured water.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 60], flower: [60, 85] }),
  },
  {
    id: 'guava',
    name: 'Guava',
    category: 'Fruits',
    varieties: ['Allahabad Safeda', 'L-49 (Sardar)', 'Lucknow 49', 'Red Fleshed', 'Shweta'],
    season: 'Perennial',
    durationDaysMin: 730,
    durationDaysMax: 1460,
    soilTypes: ['Loamy', 'Sandy Loam', 'Laterite', 'Alluvial', 'Red Loamy'],
    waterRequirement: 'Low',
    temperatureMin: 12,
    temperatureMax: 40,
    states: ['Uttar Pradesh', 'Maharashtra', 'Madhya Pradesh', 'Karnataka', 'Gujarat', 'Punjab', 'Andhra Pradesh'],
    seedRatePerAcre: '250–300 plants',
    seedCostPerAcre: { min: 9000, max: 18000 },
    cultivationCostPerAcre: { min: 20000, max: 38000 },
    expectedYieldPerAcre: { min: 80, max: 150, unit: 'quintals/acre (mature)' },
    pricePerQuintal: { min: 1800, max: 3000 },
    plantingWindows: ['Planting: Jun–Aug'],
    harvestMonths: 'Nov–Dec & Feb–Mar',
    risks: ['Fruit flies', 'Wilt in water-logged soils', 'Pre-bearing period of 2-3 years'],
    commonPests: ['Fruit fly', 'Stem borer', 'Whitefly'],
    commonDiseases: ['Wilt', 'Canker', 'Anthracnose'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Hardy, low-water fruit tree ideal for homestead orchards with multi-season harvest.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 50], flower: [50, 85] }),
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate',
    category: 'Fruits',
    varieties: ['Bhagwa', 'Ganesh', 'Mridula', 'Arakta'],
    season: 'Perennial',
    durationDaysMin: 730,
    durationDaysMax: 1095,
    soilTypes: ['Loamy', 'Sandy Loam', 'Black Cotton', 'Red Loamy'],
    waterRequirement: 'Medium',
    temperatureMin: 10,
    temperatureMax: 40,
    states: ['Maharashtra', 'Karnataka', 'Telangana', 'Andhra Pradesh', 'Gujarat', 'Rajasthan'],
    seedRatePerAcre: '300–400 plants',
    seedCostPerAcre: { min: 12000, max: 24000 },
    cultivationCostPerAcre: { min: 25000, max: 45000 },
    expectedYieldPerAcre: { min: 90, max: 140, unit: 'quintals/acre (mature)' },
    pricePerQuintal: { min: 5000, max: 9000 },
    plantingWindows: ['Planting: Jun–Aug'],
    harvestMonths: 'Jul–Sep (mrig bahar), Jan–Mar (ambia bahar)',
    risks: ['Bacterial blight (Olive knot)', 'Fruit borer', 'Needs controlled irrigation for quality', 'Long pre-bearing'],
    commonPests: ['Fruit borer', 'Aphids', 'Whitefly'],
    commonDiseases: ['Bacterial blight', 'Anthracnose'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'High-value arid fruit with good export; requires diligent disease management.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 85] }),
  },
  {
    id: 'grapes',
    name: 'Grape',
    category: 'Fruits',
    varieties: ['Thompson Seedless', 'Sharad Seedless', 'Red Globe', 'Sonaka'],
    season: 'Perennial',
    durationDaysMin: 365,
    durationDaysMax: 730,
    soilTypes: ['Sandy Loam', 'Loamy', 'Black Cotton', 'Red Loamy'],
    waterRequirement: 'Medium',
    temperatureMin: 10,
    temperatureMax: 40,
    states: ['Maharashtra', 'Karnataka', 'Telangana', 'Andhra Pradesh', 'Tamil Nadu'],
    seedRatePerAcre: '800–1000 vines',
    seedCostPerAcre: { min: 25000, max: 45000 },
    cultivationCostPerAcre: { min: 80000, max: 150000 },
    expectedYieldPerAcre: { min: 150, max: 300, unit: 'quintals/acre' },
    pricePerQuintal: { min: 4500, max: 8000 },
    plantingWindows: ['Pruning-based cropping (Nov pruning for summer crop)'],
    harvestMonths: 'Jan–Apr',
    risks: ['Very high investment', 'Powdery mildew in humidity', 'Marketing needs cold chain', 'Grapevine mealybug'],
    commonPests: ['Mealybug', 'Thrips'],
    commonDiseases: ['Powdery mildew', 'Downy mildew', 'Anthracnose'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Premium irrigated fruit requiring high skill and capital; export market rewards quality.',
    stageTemplates: stages({ germ: [10, 25], veg: [25, 60], flower: [60, 85] }),
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'Fruits',
    varieties: ['Sugar Baby', 'Arka Manik', 'Kiran', 'Asahi Yamato'],
    season: 'Zaid/Kharif',
    durationDaysMin: 80,
    durationDaysMax: 110,
    soilTypes: ['Sandy', 'Sandy Loam', 'Loamy'],
    waterRequirement: 'High',
    temperatureMin: 18,
    temperatureMax: 38,
    states: ['Andhra Pradesh', 'Telangana', 'Karnataka', 'Maharashtra', 'Uttar Pradesh', 'Odisha', 'Tamil Nadu'],
    seedRatePerAcre: '1–1.5 kg',
    seedCostPerAcre: { min: 2200, max: 4500 },
    cultivationCostPerAcre: { min: 16000, max: 28000 },
    expectedYieldPerAcre: { min: 150, max: 300, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1300, max: 2200 },
    plantingWindows: ['Zaid: Feb–Mar', 'Kharif: Jun–Jul'],
    harvestMonths: 'May–Jul (Zaid), Aug–Oct (Kharif)',
    risks: ['Fruit fly', 'Powdery mildew in humidity', 'Price dip at peak season'],
    commonPests: ['Fruit fly', 'Aphids'],
    commonDiseases: ['Fusarium wilt', 'Powdery mildew'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Quick cash fruit grown on sandy soils with drip; high tonnage per acre.',
    stageTemplates: stages({ germ: [10, 20], veg: [20, 60], flower: [60, 85] }),
  },
  {
    id: 'muskmelon',
    name: 'Muskmelon',
    category: 'Fruits',
    varieties: ['Hara Madhu', 'Punjab Sunehri', 'Kaito', 'Durgapura Madhu'],
    season: 'Zaid',
    durationDaysMin: 75,
    durationDaysMax: 100,
    soilTypes: ['Sandy Loam', 'Sandy', 'Loamy'],
    waterRequirement: 'Medium',
    temperatureMin: 18,
    temperatureMax: 38,
    states: ['Punjab', 'Haryana', 'Rajasthan', 'Uttar Pradesh', 'Madhya Pradesh', 'Karnataka', 'Andhra Pradesh'],
    seedRatePerAcre: '1–1.5 kg',
    seedCostPerAcre: { min: 1800, max: 3500 },
    cultivationCostPerAcre: { min: 14000, max: 24000 },
    expectedYieldPerAcre: { min: 120, max: 220, unit: 'quintals/acre' },
    pricePerQuintal: { min: 1400, max: 2500 },
    plantingWindows: ['Zaid: Jan–Mar'],
    harvestMonths: 'Apr–Jun',
    risks: ['Fruit fly', 'Downturn in wet spells'],
    commonPests: ['Fruit fly', 'Aphids'],
    commonDiseases: ['Powdery mildew', 'Downy mildew'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Short-cycle summer melon with good early-season prices.',
    stageTemplates: stages(),
  },
  {
    id: 'coconut',
    name: 'Coconut',
    category: 'Plantation Crops',
    varieties: ['Tall', 'Dwarf', 'West Coast Tall', 'Chandrakala', 'Kalpasree'],
    season: 'Perennial',
    durationDaysMin: 1460,
    durationDaysMax: 3650,
    soilTypes: ['Laterite', 'Sandy', 'Sandy Loam', 'Alluvial'],
    waterRequirement: 'Medium',
    temperatureMin: 20,
    temperatureMax: 34,
    states: ['Kerala', 'Tamil Nadu', 'Karnataka', 'Andhra Pradesh', 'Odisha', 'West Bengal', 'Maharashtra'],
    seedRatePerAcre: '60–80 palms',
    seedCostPerAcre: { min: 12000, max: 24000 },
    cultivationCostPerAcre: { min: 18000, max: 35000 },
    expectedYieldPerAcre: { min: 12000, max: 20000, unit: 'nuts/acre/year (mature)' },
    pricePerQuintal: { min: 2500, max: 4000 },
    plantingWindows: ['Planting: May–Jun (pre-monsoon)'],
    harvestMonths: 'Year-round, peaks Apr–Aug',
    risks: ['Very long pre-bearing (5-7 yrs)', 'Root wilt disease', 'Rodent damage to nuts'],
    commonPests: ['Rhinoceros beetle', 'Red palm weevil', 'Termites'],
    commonDiseases: ['Root wilt', 'Bud rot', 'Grey leaf blight'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Lifetime plantation crop for humid coastal zones; returns build up after years.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 85] }),
  },
  {
    id: 'arecanut',
    name: 'Arecanut',
    category: 'Plantation Crops',
    varieties: ['Mangala', 'Sreemangala', 'Mohitnagar', 'Swarnamangala'],
    season: 'Perennial',
    durationDaysMin: 2190,
    durationDaysMax: 3650,
    soilTypes: ['Laterite', 'Loamy', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: 15,
    temperatureMax: 36,
    states: ['Karnataka', 'Kerala', 'Assam', 'Meghalaya', 'Tamil Nadu'],
    seedRatePerAcre: '600–800 palms',
    seedCostPerAcre: { min: 15000, max: 30000 },
    cultivationCostPerAcre: { min: 30000, max: 55000 },
    expectedYieldPerAcre: { min: 12000, max: 22000, unit: 'nuts/acre/year (mature)' },
    pricePerQuintal: { min: 350, max: 650 },
    plantingWindows: ['Planting: May–Jun'],
    harvestMonths: 'Oct–Feb (peaks)',
    risks: ['Long pre-bearing', 'Fruit rot in monsoon', 'Price volatility', 'Needs shade and irrigation'],
    commonPests: ['Spindle bug', 'Mealybug', 'Nematodes'],
    commonDiseases: ['Koleroga (fruit rot)', 'Leaf spot'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Long-term plantation for the western coastal belt with dependable internal demand.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 85] }),
  },
  {
    id: 'cashew',
    name: 'Cashew',
    category: 'Plantation Crops',
    varieties: ['Vengurla 4', 'V-7 (Priyanka)', 'Bhaskara', 'Ullal 3'],
    season: 'Perennial',
    durationDaysMin: 1460,
    durationDaysMax: 3650,
    soilTypes: ['Laterite', 'Red Loamy', 'Sandy Loam'],
    waterRequirement: 'Low',
    temperatureMin: 15,
    temperatureMax: 38,
    states: ['Kerala', 'Karnataka', 'Maharashtra', 'Goa', 'Tamil Nadu', 'Andhra Pradesh', 'Odisha', 'West Bengal'],
    seedRatePerAcre: '160–180 plants',
    seedCostPerAcre: { min: 15000, max: 25000 },
    cultivationCostPerAcre: { min: 18000, max: 35000 },
    expectedYieldPerAcre: { min: 10, max: 25, unit: 'quintals/acre (raw nuts, mature)' },
    pricePerQuintal: { min: 7000, max: 12000 },
    plantingWindows: ['Planting: May–Jun'],
    harvestMonths: 'Feb–May',
    risks: ['Long pre-bearing (3-4 yrs)', 'Tea mosquito bug', 'Yield low on poor laterites'],
    commonPests: ['Tea mosquito bug', 'Stem borer'],
    commonDiseases: ['Dieback', 'Inflorescence blight'],
    marketDemand: 'High',
    riskLevel: 'Medium',
    description: 'Drought-tolerant plantation crop for coastal and hilly laterite belts; processed nut export demand.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 50], flower: [50, 85] }),
  },
  {
    id: 'rubber',
    name: 'Rubber',
    category: 'Plantation Crops',
    varieties: ['RRII 105', 'PB 235', 'RRIM 600', 'GT 1'],
    season: 'Perennial',
    durationDaysMin: 2190,
    durationDaysMax: 7300,
    soilTypes: ['Laterite', 'Loamy', 'Sandy Loam'],
    waterRequirement: 'High',
    temperatureMin: 20,
    temperatureMax: 34,
    states: ['Kerala', 'Tamil Nadu', 'Karnataka', 'Tripura', 'Assam', 'Nagaland', 'Meghalaya'],
    seedRatePerAcre: '120–160 trees',
    seedCostPerAcre: { min: 20000, max: 35000 },
    cultivationCostPerAcre: { min: 35000, max: 65000 },
    expectedYieldPerAcre: { min: 5, max: 10, unit: 'quintals/acre/yr (dry rubber, mature)' },
    pricePerQuintal: { min: 14000, max: 18000 },
    plantingWindows: ['Planting: May–Jul'],
    harvestMonths: 'Year-round tapping excl. heavy rain',
    risks: ['7-year gestation', 'Price linked to global markets', 'Tapping labour', 'Wind damage'],
    commonPests: ['Pink disease', 'Mealybug'],
    commonDiseases: ['Abnormal leaf fall', 'Tapping panel dryness'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Long-gestation industrial plantation for humid regions; income only after ~7 years.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 85] }),
  },
  {
    id: 'coffee',
    name: 'Coffee',
    category: 'Plantation Crops',
    varieties: ['Arabica (S.795, Catimor)', 'Robusta (CxR)', 'Cauvery'],
    season: 'Perennial',
    durationDaysMin: 1460,
    durationDaysMax: 3650,
    soilTypes: ['Laterite', 'Loamy', 'Red Loamy'],
    waterRequirement: 'High',
    temperatureMin: 12,
    temperatureMax: 30,
    states: ['Karnataka', 'Kerala', 'Tamil Nadu', 'Andhra Pradesh', 'Odisha'],
    seedRatePerAcre: '800–1000 plants (coffee under shade)',
    seedCostPerAcre: { min: 25000, max: 50000 },
    cultivationCostPerAcre: { min: 35000, max: 70000 },
    expectedYieldPerAcre: { min: 6, max: 12, unit: 'quintals/acre (cherry)' },
    pricePerQuintal: { min: 16000, max: 24000 },
    plantingWindows: ['Planting: Jun–Aug'],
    harvestMonths: 'Nov–Feb (peaks Dec–Jan)',
    risks: ['Long pre-bearing', 'Berry borer', 'Needs elevation & shade', 'White stem borer in dry zones'],
    commonPests: ['Coffee berry borer', 'White stem borer'],
    commonDiseases: ['Leaf rust', 'Brown blight'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Premium plantation crop for the Western Ghats; value addition through specialty roasting.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 85] }),
  },
  {
    id: 'tea',
    name: 'Tea',
    category: 'Plantation Crops',
    varieties: ['Assam', 'China', 'TV 1', 'TV 23', 'Cambod'],
    season: 'Perennial',
    durationDaysMin: 2190,
    durationDaysMax: 7300,
    soilTypes: ['Laterite', 'Loamy', 'Sandy Loam'],
    waterRequirement: 'High',
    temperatureMin: 16,
    temperatureMax: 32,
    states: ['Assam', 'West Bengal', 'Tamil Nadu', 'Kerala', 'Himachal Pradesh', 'Uttarakhand'],
    seedRatePerAcre: '3000–5000 cuttings',
    seedCostPerAcre: { min: 30000, max: 60000 },
    cultivationCostPerAcre: { min: 50000, max: 90000 },
    expectedYieldPerAcre: { min: 8, max: 16, unit: 'quintals/acre/yr (made tea)' },
    pricePerQuintal: { min: 12000, max: 20000 },
    plantingWindows: ['Planting: Jun–Sep'],
    harvestMonths: 'Year-round plucking (peak May–Oct)',
    risks: ['Very long gestation', 'Plucking labour intensive', 'Blister blight', 'Price cycles'],
    commonPests: ['Tea mosquito bug', 'Red spider mite'],
    commonDiseases: ['Blister blight', 'Root rot'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Industrial plantation with continuous plucking cycle; suited to high-rainfall hill belts.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 60], flower: [60, 90] }),
  },
  {
    id: 'cocoa',
    name: 'Cocoa',
    category: 'Plantation Crops',
    varieties: ['Forastero', 'Criollo', 'Trinitario'],
    season: 'Perennial',
    durationDaysMin: 1095,
    durationDaysMax: 3650,
    soilTypes: ['Laterite', 'Loamy', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: 20,
    temperatureMax: 35,
    states: ['Kerala', 'Karnataka', 'Tamil Nadu', 'Andhra Pradesh', 'Telangana'],
    seedRatePerAcre: '400–500 plants (under arecanut/coconut)',
    seedCostPerAcre: { min: 15000, max: 30000 },
    cultivationCostPerAcre: { min: 25000, max: 45000 },
    expectedYieldPerAcre: { min: 5, max: 10, unit: 'quintals/acre (dry beans)' },
    pricePerQuintal: { min: 95000, max: 160000 },
    plantingWindows: ['Planting: May–Jun'],
    harvestMonths: 'Year-round (peak Oct–Feb)',
    risks: ['Long pre-bearing (3-4 yrs)', 'Pod rot in monsoon', 'Needs shade crop', 'Black pod disease'],
    commonPests: ['Cocoa pod borer', 'Mirid bug', 'Meadow hopper'],
    commonDiseases: ['Black pod', 'Witches broom'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Intercrop under arecanut/coconut promising strong price; requires skilled pod management.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 85] }),
  },
  {
    id: 'cardamom',
    name: 'Cardamom (Elaichi)',
    category: 'Spices',
    varieties: ['Njallani', 'ICRI 1', 'ICRI 2', 'PV 1'],
    season: 'Perennial',
    durationDaysMin: 1095,
    durationDaysMax: 3650,
    soilTypes: ['Laterite', 'Loamy', 'Clay Loam'],
    waterRequirement: 'High',
    temperatureMin: 12,
    temperatureMax: 30,
    states: ['Kerala', 'Karnataka', 'Tamil Nadu'],
    seedRatePerAcre: '1000–1200 plants',
    seedCostPerAcre: { min: 20000, max: 40000 },
    cultivationCostPerAcre: { min: 40000, max: 75000 },
    expectedYieldPerAcre: { min: 2, max: 5, unit: 'quintals/acre (capsule)' },
    pricePerQuintal: { min: 150000, max: 250000 },
    plantingWindows: ['Planting: May–Jun'],
    harvestMonths: 'Sep–Dec',
    risks: ['Very high value but extreme price swings', 'Panicle/capsule rot in wet spells', 'Thrips', 'Long gestation'],
    commonPests: ['Thrips', 'Root grub', 'Shoot borer'],
    commonDiseases: ['Capsule rot', 'Clump rot', 'Leaf blight'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: '"Queen of spices" for high-altitude evergreen belts; intense management and market swings.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 85] }),
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruits',
    varieties: ['Delicious', 'Kinnaur', 'Ambri', 'Fuji', 'Gala'],
    season: 'Perennial',
    durationDaysMin: 1460,
    durationDaysMax: 3650,
    soilTypes: ['Loamy', 'Sandy Loam', 'Alluvial'],
    waterRequirement: 'High',
    temperatureMin: -5,
    temperatureMax: 32,
    states: ['Himachal Pradesh', 'Jammu & Kashmir', 'Uttarakhand', 'Arunachal Pradesh', 'Jharkhand'],
    seedRatePerAcre: '170–350 plants (dwarf-high density)',
    seedCostPerAcre: { min: 30000, max: 60000 },
    cultivationCostPerAcre: { min: 45000, max: 90000 },
    expectedYieldPerAcre: { min: 60, max: 120, unit: 'quintals/acre (mature)' },
    pricePerQuintal: { min: 6000, max: 12000 },
    plantingWindows: ['Planting: Dec–Jan (dormant)'],
    harvestMonths: 'Jul–Oct',
    risks: ['Needs high-altitude chilling', 'Scab in humid valleys', 'Hail damage', 'Long pre-bearing'],
    commonPests: ['San Jose scale', 'Codling moth', 'Aphids'],
    commonDiseases: ['Apple scab', 'Powdery mildew', 'Fire blight'],
    marketDemand: 'High',
    riskLevel: 'High',
    description: 'Temperate fruit for Himalayan belts with winter chilling hours; brand-value premium cultivars.',
    stageTemplates: stages({ germ: [5, 15], veg: [15, 55], flower: [55, 85] }),
  },
  ];

export const SHIPPED_CROP_KNOWLEDGE: CropKnowledgeEntry[] = CROP_KNOWLEDGE;